# frozen_string_literal: true

module Pangea
  module Resources
    # Aggregator module that includes all Cloudflare resource modules.
    # Each resource file reopens this module and includes itself,
    # so by the time this file is loaded all resource modules are
    # already mixed in. This file exists as a single entry point
    # for consumers who want `include Pangea::Resources::Cloudflare`.
    module Cloudflare
      include CloudflareAccessRule
      include CloudflareAccount
      include CloudflareAccountDnsSettings
      include CloudflareAccountDnsSettingsInternalView
      include CloudflareAccountMember
      include CloudflareAccountSubscription
      include CloudflareAccountToken
      include CloudflareAddressMap
      include CloudflareApiShield
      include CloudflareApiShieldDiscoveryOperation
      include CloudflareApiShieldOperation
      include CloudflareApiShieldOperationSchemaValidationSettings
      include CloudflareApiShieldSchema
      include CloudflareApiShieldSchemaValidationSettings
      include CloudflareApiToken
      include CloudflareArgo
      include CloudflareAuthenticatedOriginPulls
      include CloudflareAuthenticatedOriginPullsCertificate
      include CloudflareAuthenticatedOriginPullsSettings
      include CloudflareBotManagement
      include CloudflareByoIpPrefix
      include CloudflareCallsSfuApp
      include CloudflareCallsTurnApp
      include CloudflareCertificatePack
      include CloudflareCloudConnectorRules
      include CloudflareCloudforceOneRequest
      include CloudflareCloudforceOneRequestAsset
      include CloudflareCloudforceOneRequestMessage
      include CloudflareCloudforceOneRequestPriority
      include CloudflareContentScanning
      include CloudflareContentScanningExpression
      include CloudflareCustomHostname
      include CloudflareCustomHostnameFallbackOrigin
      include CloudflareCustomPages
      include CloudflareCustomSsl
      include CloudflareD1Database
      include CloudflareDnsFirewall
      include CloudflareDnsZoneTransfersAcl
      include CloudflareDnsZoneTransfersIncoming
      include CloudflareDnsZoneTransfersOutgoing
      include CloudflareDnsZoneTransfersPeer
      include CloudflareDnsZoneTransfersTsig
      include CloudflareEmailRoutingAddress
      include CloudflareEmailRoutingCatchAll
      include CloudflareEmailRoutingDns
      include CloudflareEmailRoutingRule
      include CloudflareEmailRoutingSettings
      include CloudflareEmailSecurityBlockSender
      include CloudflareEmailSecurityImpersonationRegistry
      include CloudflareEmailSecurityTrustedDomains
      include CloudflareFilter
      include CloudflareFirewallRule
      include CloudflareHealthcheck
      include CloudflareHostnameTlsSetting
      include CloudflareHyperdriveConfig
      include CloudflareImage
      include CloudflareImageVariant
      include CloudflareKeylessCertificate
      include CloudflareLeakedCredentialCheck
      include CloudflareLeakedCredentialCheckRule
      include CloudflareList
      include CloudflareListItem
      include CloudflareLoadBalancer
      include CloudflareLoadBalancerMonitor
      include CloudflareLoadBalancerPool
      include CloudflareLogpullRetention
      include CloudflareLogpushJob
      include CloudflareLogpushOwnershipChallenge
      include CloudflareMagicNetworkMonitoringConfiguration
      include CloudflareMagicNetworkMonitoringRule
      include CloudflareMagicTransitConnector
      include CloudflareMagicTransitSite
      include CloudflareMagicTransitSiteAcl
      include CloudflareMagicTransitSiteLan
      include CloudflareMagicTransitSiteWan
      include CloudflareMagicWanGreTunnel
      include CloudflareMagicWanIpsecTunnel
      include CloudflareMagicWanStaticRoute
      include CloudflareManagedTransforms
      include CloudflareMtlsCertificate
      include CloudflareNotificationPolicy
      include CloudflareNotificationPolicyWebhooks
      include CloudflareObservatoryScheduledTest
      include CloudflareOrganization
      include CloudflareOrganizationProfile
      include CloudflareOriginCACertificate
      include CloudflarePageRule
      include CloudflarePageShieldPolicy
      include CloudflarePagesDomain
      include CloudflarePagesProject
      include CloudflareQueue
      include CloudflareQueueConsumer
      include CloudflareR2Bucket
      include CloudflareR2BucketCors
      include CloudflareR2BucketEventNotification
      include CloudflareR2BucketLifecycle
      include CloudflareR2BucketLock
      include CloudflareR2BucketSippy
      include CloudflareR2CustomDomain
      include CloudflareR2ManagedDomain
      include CloudflareRateLimit
      include CloudflareRecord
      include CloudflareRegionalHostname
      include CloudflareRegionalTieredCache
      include CloudflareRegistrarDomain
      include CloudflareRuleset
      include CloudflareSchemaValidationOperationSettings
      include CloudflareSchemaValidationSchemas
      include CloudflareSchemaValidationSettings
      include CloudflareSnippet
      include CloudflareSnippetRules
      include CloudflareSpectrumApplication
      include CloudflareStaticRoute
      include CloudflareStream
      include CloudflareStreamAudioTrack
      include CloudflareStreamCaptionLanguage
      include CloudflareStreamDownload
      include CloudflareStreamKey
      include CloudflareStreamLiveInput
      include CloudflareStreamWatermark
      include CloudflareStreamWebhook
      include CloudflareTieredCache
      include CloudflareTotalTls
      include CloudflareTurnstileWidget
      include CloudflareURLNormalizationSettings
      include CloudflareUser
      include CloudflareUserAgentBlockingRule
      include CloudflareWaitingRoom
      include CloudflareWaitingRoomEvent
      include CloudflareWaitingRoomRules
      include CloudflareWaitingRoomSettings
      include CloudflareWeb3Hostname
      include CloudflareWebAnalyticsRule
      include CloudflareWebAnalyticsSite
      include CloudflareWorker
      include CloudflareWorkerRoute
      include CloudflareWorkerScript
      include CloudflareWorkerVersion
      include CloudflareWorkersCronTrigger
      include CloudflareWorkersCustomDomain
      include CloudflareWorkersDeployment
      include CloudflareWorkersForPlatformsDispatchNamespace
      include CloudflareWorkersKv
      include CloudflareWorkersKvNamespace
      include CloudflareWorkersScriptSubdomain
      include CloudflareWorkflow
      include CloudflareZeroTrustAccessApplication
      include CloudflareZeroTrustAccessCustomPage
      include CloudflareZeroTrustAccessGroup
      include CloudflareZeroTrustAccessIdentityProvider
      include CloudflareZeroTrustAccessInfrastructureTarget
      include CloudflareZeroTrustAccessKeyConfiguration
      include CloudflareZeroTrustAccessMtlsCertificate
      include CloudflareZeroTrustAccessMtlsHostnameSettings
      include CloudflareZeroTrustAccessPolicy
      include CloudflareZeroTrustAccessServiceToken
      include CloudflareZeroTrustAccessShortLivedCertificate
      include CloudflareZeroTrustAccessTag
      include CloudflareDeviceCustomProfile
      include CloudflareDeviceCustomProfileLocalDomainFallback
      include CloudflareDeviceDefaultProfile
      include CloudflareDeviceDefaultProfileCertificates
      include CloudflareDeviceDefaultProfileLocalDomainFallback
      include CloudflareZeroTrustDeviceManagedNetworks
      include CloudflareZeroTrustDevicePostureIntegration
      include CloudflareZeroTrustDevicePostureRule
      include CloudflareZeroTrustDeviceSettings
      include CloudflareZeroTrustDexTest
      include CloudflareZeroTrustDlpCustomEntry
      include CloudflareZeroTrustDlpCustomProfile
      include CloudflareZeroTrustDlpDataset
      include CloudflareZeroTrustDlpEntry
      include CloudflareZeroTrustDlpIntegrationEntry
      include CloudflareZeroTrustDlpPredefinedEntry
      include CloudflareZeroTrustDlpPredefinedProfile
      include CloudflareZeroTrustDnsLocation
      include CloudflareZeroTrustGatewayCertificate
      include CloudflareZeroTrustGatewayLogging
      include CloudflareZeroTrustGatewayPolicy
      include CloudflareZeroTrustGatewayProxyEndpoint
      include CloudflareZeroTrustGatewaySettings
      include CloudflareZeroTrustList
      include CloudflareZeroTrustNetworkHostnameRoute
      include CloudflareZeroTrustOrganization
      include CloudflareZeroTrustRiskBehavior
      include CloudflareZeroTrustRiskScoringIntegration
      include CloudflareZeroTrustTunnelCloudflared
      include CloudflareZeroTrustTunnelCloudflaredConfig
      include CloudflareZeroTrustTunnelCloudflaredRoute
      include CloudflareZeroTrustTunnelCloudflaredVirtualNetwork
      include CloudflareZeroTrustTunnelWarpConnector
      include CloudflareZone
      include CloudflareZoneCacheReserve
      include CloudflareZoneCacheVariants
      include CloudflareZoneDnsSettings
      include CloudflareZoneDnssec
      include CloudflareZoneHold
      include CloudflareZoneLockdown
      include CloudflareZoneSettingsOverride
      include CloudflareZoneSubscription
    end
  end
end
