# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_load_balancer infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_load_balancer/ -t cloudflare://

control 'cloudflare_load_balancer-exists' do
  impact 1.0
  title 'Manages a cloudflare_load_balancer resource'
  desc 'Verify that the cloudflare_load_balancer resource exists and has expected properties'

  describe cloudflare_load_balancer(name: attribute('id')) do
    it { should exist }
    its('default_pools') { should_not be_nil }
    its('fallback_pool') { should_not be_nil }
    its('name') { should_not be_nil }
    its('zone_id') { should_not be_nil }
  end
end
