# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_authenticated_origin_pulls_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareAuthenticatedOriginPullsCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_authenticated_origin_pulls_certificate,
      attributes_class: Cloudflare::Types::AuthenticatedOriginPullsCertificateAttributes,
      outputs: { id: :id },
      map: [:certificate, :private_key, :zone_id]
  end
  module Cloudflare
    include CloudflareAuthenticatedOriginPullsCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
