# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_logpush_job infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_logpush_job/ -t cloudflare://

control 'cloudflare_logpush_job-exists' do
  impact 1.0
  title 'Manages a cloudflare_logpush_job resource'
  desc 'Verify that the cloudflare_logpush_job resource exists and has expected properties'

  describe cloudflare_logpush_job(name: attribute('id')) do
    it { should exist }
    its('destination_conf') { should_not be_nil }
  end
end
