# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_gateway_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustGatewaySettings
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_gateway_settings,
      attributes_class: Cloudflare::Types::ZeroTrustGatewaySettingsAttributes,
      outputs: { id: :id },
      map: [:account_id],
      map_present: [:settings]
  end
  module Cloudflare
    include CloudflareZeroTrustGatewaySettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
