# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_magic_wan_static_route infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_magic_wan_static_route/ -t cloudflare://

control 'cloudflare_magic_wan_static_route-exists' do
  impact 1.0
  title 'Manages a cloudflare_magic_wan_static_route resource'
  desc 'Verify that the cloudflare_magic_wan_static_route resource exists and has expected properties'

  describe cloudflare_magic_wan_static_route(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('nexthop') { should_not be_nil }
    its('prefix') { should_not be_nil }
    its('priority') { should_not be_nil }
  end
end
