# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_workers_kv infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_workers_kv/ -t cloudflare://

control 'cloudflare_workers_kv-exists' do
  impact 1.0
  title 'Manages a cloudflare_workers_kv resource'
  desc 'Verify that the cloudflare_workers_kv resource exists and has expected properties'

  describe cloudflare_workers_kv(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('key_name') { should_not be_nil }
    its('namespace_id') { should_not be_nil }
    its('value') { should_not be_nil }
  end
end
