# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_tiered_cache/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareTieredCache
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_tiered_cache,
      attributes_class: Cloudflare::Types::TieredCacheAttributes,
      outputs: { id: :id },
      map: [:value, :zone_id]
  end
  module Cloudflare
    include CloudflareTieredCache
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
