# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zone_lockdown/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZoneLockdown
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zone_lockdown,
      attributes_class: Cloudflare::Types::ZoneLockdownAttributes,
      outputs: { id: :id },
      map: [:configurations, :urls, :zone_id],
      map_present: [:description, :priority],
      map_bool: [:paused]
  end
  module Cloudflare
    include CloudflareZoneLockdown
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
