# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_sso_connector/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareSsoConnector
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_sso_connector,
      attributes_class: Cloudflare::Types::SsoConnectorAttributes,
      outputs: { id: :id },
      map: [:account_id, :email_domain],
      map_bool: [:begin_verification, :enabled, :use_fedramp_language]
  end
  module Cloudflare
    include CloudflareSsoConnector
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
