# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_managed_transforms/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareManagedTransforms
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_managed_transforms,
      attributes_class: Cloudflare::Types::ManagedTransformsAttributes,
      outputs: { id: :id },
      map: [:managed_request_headers, :managed_response_headers, :zone_id]
  end
  module Cloudflare
    include CloudflareManagedTransforms
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
