# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_cloudforce_one_request_priority/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareCloudforceOneRequestPriority
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_cloudforce_one_request_priority,
      attributes_class: Cloudflare::Types::CloudforceOneRequestPriorityAttributes,
      outputs: { id: :id },
      map: [:account_id, :labels, :priority, :requirement, :tlp]
  end
  module Cloudflare
    include CloudflareCloudforceOneRequestPriority
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
