# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class CloudforceOneRequestPriorityAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :labels, T::Array.of(T::String)
    attribute :priority, (T::Coercible::Integer | T::Coercible::Float)
    attribute :requirement, T::String
    attribute :tlp, T::String
  end
end
