# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zone_dns_settings infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zone_dns_settings/ -t cloudflare://

control 'cloudflare_zone_dns_settings-exists' do
  impact 1.0
  title 'Manages a cloudflare_zone_dns_settings resource'
  desc 'Verify that the cloudflare_zone_dns_settings resource exists and has expected properties'

  describe cloudflare_zone_dns_settings(name: attribute('id')) do
    it { should exist }
    its('zone_id') { should_not be_nil }
  end
end
