# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_magic_transit_site_wan/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareMagicTransitSiteWan
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_magic_transit_site_wan,
      attributes_class: Cloudflare::Types::MagicTransitSiteWanAttributes,
      outputs: { id: :id },
      map: [:account_id, :physport, :site_id],
      map_present: [:name, :priority, :static_addressing, :vlan_tag]
  end
  module Cloudflare
    include CloudflareMagicTransitSiteWan
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
