# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zero_trust_access_identity_provider infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zero_trust_access_identity_provider/ -t cloudflare://

control 'cloudflare_zero_trust_access_identity_provider-exists' do
  impact 1.0
  title 'Manages a cloudflare_zero_trust_access_identity_provider resource'
  desc 'Verify that the cloudflare_zero_trust_access_identity_provider resource exists and has expected properties'

  describe cloudflare_zero_trust_access_identity_provider(name: attribute('id')) do
    it { should exist }
    its('config') { should_not be_nil }
    its('name') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
