# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_r2_bucket_event_notification/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareR2BucketEventNotification
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_r2_bucket_event_notification,
      attributes_class: Cloudflare::Types::R2BucketEventNotificationAttributes,
      outputs: { id: :id },
      map: [:account_id, :bucket_name, :queue_id, :rules],
      map_present: [:jurisdiction]
  end
  module Cloudflare
    include CloudflareR2BucketEventNotification
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
