# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class R2BucketEventNotificationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :bucket_name, T::String
    attribute :queue_id, T::String
    attribute :rules, T::Array.of(T::Hash)
    attribute? :jurisdiction, T::String.optional
  end
end
