# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_byo_ip_prefix infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_byo_ip_prefix/ -t cloudflare://

control 'cloudflare_byo_ip_prefix-exists' do
  impact 1.0
  title 'Manages a cloudflare_byo_ip_prefix resource'
  desc 'Verify that the cloudflare_byo_ip_prefix resource exists and has expected properties'

  describe cloudflare_byo_ip_prefix(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('asn') { should_not be_nil }
    its('cidr') { should_not be_nil }
  end
end
