# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_tunnel_cloudflared_virtual_network/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustTunnelCloudflaredVirtualNetwork
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_tunnel_cloudflared_virtual_network,
      attributes_class: Cloudflare::Types::ZeroTrustTunnelCloudflaredVirtualNetworkAttributes,
      outputs: { id: :id },
      map: [:account_id, :name],
      map_present: [:comment],
      map_bool: [:is_default, :is_default_network]
  end
  module Cloudflare
    include CloudflareZeroTrustTunnelCloudflaredVirtualNetwork
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
