# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_filter infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_filter/ -t cloudflare://

control 'cloudflare_filter-exists' do
  impact 1.0
  title 'Manages a cloudflare_filter resource'
  desc 'Verify that the cloudflare_filter resource exists and has expected properties'

  describe cloudflare_filter(name: attribute('id')) do
    it { should exist }
    its('body') { should_not be_nil }
    its('zone_id') { should_not be_nil }
  end
end
