# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_load_balancer_monitor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareLoadBalancerMonitor
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_load_balancer_monitor,
      attributes_class: Cloudflare::Types::LoadBalancerMonitorAttributes,
      outputs: { id: :id },
      map: [:account_id],
      map_present: [:consecutive_down, :consecutive_up, :description, :expected_body, :expected_codes, :header, :interval, :method, :path, :port, :probe_zone, :retries, :timeout, :type],
      map_bool: [:allow_insecure, :follow_redirects]
  end
  module Cloudflare
    include CloudflareLoadBalancerMonitor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
