# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class LoadBalancerMonitorAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute? :allow_insecure, T::Bool.optional
    attribute? :consecutive_down, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :consecutive_up, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :description, T::String.optional
    attribute? :expected_body, T::String.optional
    attribute? :expected_codes, T::String.optional
    attribute? :follow_redirects, T::Bool.optional
    attribute? :header, T::Hash.optional
    attribute? :interval, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :method, T::String.optional
    attribute? :path, T::String.optional
    attribute? :port, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :probe_zone, T::String.optional
    attribute? :retries, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :timeout, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :type, T::String.optional
  end
end
