# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class SnippetRulesAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :rules, T::Array.of(T::Hash)
    attribute :zone_id, T::String
  end
end
