# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_ruleset/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareRuleset
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_ruleset,
      attributes_class: Cloudflare::Types::RulesetAttributes,
      outputs: { id: :id },
      map: [:kind, :name, :phase],
      map_present: [:account_id, :description, :rules, :zone_id]
  end
  module Cloudflare
    include CloudflareRuleset
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
