# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_gateway_logging/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustGatewayLogging
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_gateway_logging,
      attributes_class: Cloudflare::Types::ZeroTrustGatewayLoggingAttributes,
      outputs: { id: :id },
      map: [:account_id],
      map_present: [:settings_by_rule_type],
      map_bool: [:redact_pii]
  end
  module Cloudflare
    include CloudflareZeroTrustGatewayLogging
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
