# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZeroTrustAccessGroupAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :include, T::Array.of(T::Hash)
    attribute :name, T::String
    attribute? :account_id, T::String.optional
    attribute? :exclude, T::Array.of(T::Hash).optional
    attribute? :is_default, T::Bool.optional
    attribute? :require, T::Array.of(T::Hash).optional
    attribute? :zone_id, T::String.optional
  end
end
