# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_total_tls/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareTotalTls
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_total_tls,
      attributes_class: Cloudflare::Types::TotalTlsAttributes,
      outputs: { id: :id },
      map: [:zone_id],
      map_present: [:certificate_authority],
      map_bool: [:enabled]
  end
  module Cloudflare
    include CloudflareTotalTls
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
