# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_snippets infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_snippets/ -t cloudflare://

control 'cloudflare_snippets-exists' do
  impact 1.0
  title 'Manages a cloudflare_snippets resource'
  desc 'Verify that the cloudflare_snippets resource exists and has expected properties'

  describe cloudflare_snippets(name: attribute('id')) do
    it { should exist }
    its('files') { should_not be_nil }
    its('metadata') { should_not be_nil }
    its('snippet_name') { should_not be_nil }
    its('zone_id') { should_not be_nil }
  end
end
