# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class WaitingRoomAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :host, T::String
    attribute :name, T::String
    attribute :new_users_per_minute, (T::Coercible::Integer | T::Coercible::Float)
    attribute :total_active_users, (T::Coercible::Integer | T::Coercible::Float)
    attribute :zone_id, T::String
    attribute? :additional_routes, T::Array.of(T::Hash).optional
    attribute? :cookie_attributes, T::Hash.optional
    attribute? :cookie_suffix, T::String.optional
    attribute? :custom_page_html, T::String.optional
    attribute? :default_template_language, T::String.optional
    attribute? :description, T::String.optional
    attribute? :disable_session_renewal, T::Bool.optional
    attribute? :enabled_origin_commands, T::Array.of(T::String).optional
    attribute? :json_response_enabled, T::Bool.optional
    attribute? :path, T::String.optional
    attribute? :queue_all, T::Bool.optional
    attribute? :queueing_method, T::String.optional
    attribute? :queueing_status_code, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :session_duration, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :suspended, T::Bool.optional
    attribute? :turnstile_action, T::String.optional
    attribute? :turnstile_mode, T::String.optional
  end
end
