# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zero_trust_access_group infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zero_trust_access_group/ -t cloudflare://

control 'cloudflare_zero_trust_access_group-exists' do
  impact 1.0
  title 'Manages a cloudflare_zero_trust_access_group resource'
  desc 'Verify that the cloudflare_zero_trust_access_group resource exists and has expected properties'

  describe cloudflare_zero_trust_access_group(name: attribute('id')) do
    it { should exist }
    its('include') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
