# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_custom_origin_trust_store/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareCustomOriginTrustStore
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_custom_origin_trust_store,
      attributes_class: Cloudflare::Types::CustomOriginTrustStoreAttributes,
      outputs: { id: :id },
      map: [:certificate, :zone_id]
  end
  module Cloudflare
    include CloudflareCustomOriginTrustStore
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
