# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class PageShieldPolicyAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :action, T::String
    attribute :description, T::String
    attribute :enabled, T::Bool
    attribute :expression, T::String
    attribute :value, T::String
    attribute :zone_id, T::String
  end
end
