# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class WebAnalyticsSiteAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute? :auto_install, T::Bool.optional
    attribute? :enabled, T::Bool.optional
    attribute? :host, T::String.optional
    attribute? :lite, T::Bool.optional
    attribute? :zone_tag, T::String.optional
  end
end
