# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_device_settings/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustDeviceSettings
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_device_settings,
      attributes_class: Cloudflare::Types::ZeroTrustDeviceSettingsAttributes,
      outputs: { id: :id },
      map: [:account_id],
      map_present: [:disable_for_time, :external_emergency_signal_fingerprint, :external_emergency_signal_interval, :external_emergency_signal_url],
      map_bool: [:external_emergency_signal_enabled, :gateway_proxy_enabled, :gateway_udp_proxy_enabled, :root_certificate_installation_enabled, :use_zt_virtual_ip]
  end
  module Cloudflare
    include CloudflareZeroTrustDeviceSettings
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
