# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class UserAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute? :country, T::String.optional
    attribute? :first_name, T::String.optional
    attribute? :last_name, T::String.optional
    attribute? :telephone, T::String.optional
    attribute? :zipcode, T::String.optional
  end
end
