# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_device_default_profile/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustDeviceDefaultProfile
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_device_default_profile,
      attributes_class: Cloudflare::Types::ZeroTrustDeviceDefaultProfileAttributes,
      outputs: { id: :id },
      map: [:account_id],
      map_present: [:auto_connect, :captive_portal, :exclude, :include, :lan_allow_minutes, :lan_allow_subnet_size, :service_mode_v2, :support_url, :tunnel_protocol],
      map_bool: [:allow_mode_switch, :allow_updates, :allowed_to_leave, :disable_auto_fallback, :exclude_office_ips, :register_interface_ip_with_dns, :sccm_vpn_boundary_support, :switch_locked]
  end
  module Cloudflare
    include CloudflareZeroTrustDeviceDefaultProfile
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
