# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class WorkerAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :name, T::String
    attribute? :logpush, T::Bool.optional
    attribute? :observability, T::Hash.optional
    attribute? :subdomain, T::Hash.optional
    attribute? :tags, T::Array.of(T::String).optional
    attribute? :tail_consumers, T::Array.of(T::Hash).optional
  end
end
