# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zero_trust_organization infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zero_trust_organization/ -t cloudflare://

control 'cloudflare_zero_trust_organization-exists' do
  impact 1.0
  title 'Manages a cloudflare_zero_trust_organization resource'
  desc 'Verify that the cloudflare_zero_trust_organization resource exists and has expected properties'

  describe cloudflare_zero_trust_organization(name: attribute('id')) do
    it { should exist }
  end
end
