# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class MtlsCertificateAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :ca, T::Bool
    attribute :certificates, T::String
    attribute? :name, T::String.optional
    attribute? :private_key, T::String.optional
  end
end
