# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class LoadBalancerPoolAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :name, T::String
    attribute :origins, T::Array.of(T::Hash)
    attribute? :check_regions, T::Array.of(T::String).optional
    attribute? :description, T::String.optional
    attribute? :enabled, T::Bool.optional
    attribute? :latitude, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :load_shedding, T::Hash.optional
    attribute? :longitude, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :minimum_origins, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :monitor, T::String.optional
    attribute? :monitor_group, T::String.optional
    attribute? :notification_email, T::String.optional
    attribute? :notification_filter, T::Hash.optional
    attribute? :origin_steering, T::Hash.optional
  end
end
