# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zero_trust_device_default_profile_local_domain_fallback infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zero_trust_device_default_profile_local_domain_fallback/ -t cloudflare://

control 'cloudflare_zero_trust_device_default_profile_local_domain_fallback-exists' do
  impact 1.0
  title 'Manages a cloudflare_zero_trust_device_default_profile_local_domain_fallback resource'
  desc 'Verify that the cloudflare_zero_trust_device_default_profile_local_domain_fallback resource exists and has expected properties'

  describe cloudflare_zero_trust_device_default_profile_local_domain_fallback(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('domains') { should_not be_nil }
  end
end
