# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_stream_live_input infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_stream_live_input/ -t cloudflare://

control 'cloudflare_stream_live_input-exists' do
  impact 1.0
  title 'Manages a cloudflare_stream_live_input resource'
  desc 'Verify that the cloudflare_stream_live_input resource exists and has expected properties'

  describe cloudflare_stream_live_input(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
  end
end
