# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_ai_search_instance infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_ai_search_instance/ -t cloudflare://

control 'cloudflare_ai_search_instance-exists' do
  impact 1.0
  title 'Manages a cloudflare_ai_search_instance resource'
  desc 'Verify that the cloudflare_ai_search_instance resource exists and has expected properties'

  describe cloudflare_ai_search_instance(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('id') { should_not be_nil }
    its('source') { should_not be_nil }
    its('type') { should_not be_nil }
  end
end
