# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZoneSubscriptionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :zone_id, T::String
    attribute? :frequency, T::String.optional
    attribute? :rate_plan, T::Hash.optional
  end
end
