# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zone_dnssec/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZoneDnssec
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zone_dnssec,
      attributes_class: Cloudflare::Types::ZoneDnssecAttributes,
      outputs: { id: :id },
      map: [:zone_id],
      map_present: [:status],
      map_bool: [:dnssec_multi_signer, :dnssec_presigned, :dnssec_use_nsec3]
  end
  module Cloudflare
    include CloudflareZoneDnssec
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
