# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZoneDnssecAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :zone_id, T::String
    attribute? :dnssec_multi_signer, T::Bool.optional
    attribute? :dnssec_presigned, T::Bool.optional
    attribute? :dnssec_use_nsec3, T::Bool.optional
    attribute? :status, T::String.optional
  end
end
