# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZeroTrustRiskScoringIntegrationAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :integration_type, T::String
    attribute :tenant_url, T::String
    attribute? :active, T::Bool.optional
    attribute? :reference_id, T::String.optional
  end
end
