# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_worker_version/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareWorkerVersion
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_worker_version,
      attributes_class: Cloudflare::Types::WorkerVersionAttributes,
      outputs: { id: :id },
      map: [:account_id, :worker_id],
      map_present: [:annotations, :assets, :bindings, :compatibility_date, :compatibility_flags, :limits, :main_module, :migrations, :modules, :placement, :usage_model]
  end
  module Cloudflare
    include CloudflareWorkerVersion
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
