# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class WorkerVersionAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :worker_id, T::String
    attribute? :annotations, T::Hash.optional
    attribute? :assets, T::Hash.optional
    attribute? :bindings, T::Array.of(T::Hash).optional
    attribute? :compatibility_date, T::String.optional
    attribute? :compatibility_flags, T::Array.of(T::String).optional
    attribute? :limits, T::Hash.optional
    attribute? :main_module, T::String.optional
    attribute? :migrations, T::Hash.optional
    attribute? :modules, T::Array.of(T::Hash).optional
    attribute? :placement, T::Hash.optional
    attribute? :usage_model, T::String.optional
  end
end
