# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_user infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_user/ -t cloudflare://

control 'cloudflare_user-exists' do
  impact 1.0
  title 'Manages a cloudflare_user resource'
  desc 'Verify that the cloudflare_user resource exists and has expected properties'

  describe cloudflare_user(name: attribute('id')) do
    it { should exist }
  end
end
