# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ListItemAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :list_id, T::String
    attribute? :asn, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :comment, T::String.optional
    attribute? :hostname, T::Hash.optional
    attribute? :ip, T::String.optional
    attribute? :redirect, T::Hash.optional
  end
end
