# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class DnsRecordAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :name, T::String
    attribute :ttl, (T::Coercible::Integer | T::Coercible::Float)
    attribute :type, T::String
    attribute :zone_id, T::String
    attribute? :comment, T::String.optional
    attribute? :content, T::String.optional
    attribute? :data, T::Hash.optional
    attribute? :priority, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :proxied, T::Bool.optional
    attribute? :settings, T::Hash.optional
    attribute? :tags, T::Array.of(T::String).optional
  end
end
