# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_workers_route/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareWorkersRoute
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_workers_route,
      attributes_class: Cloudflare::Types::WorkersRouteAttributes,
      outputs: { id: :id },
      map: [:pattern, :zone_id],
      map_present: [:script]
  end
  module Cloudflare
    include CloudflareWorkersRoute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
