# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_tunnel_cloudflared_route/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustTunnelCloudflaredRoute
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_tunnel_cloudflared_route,
      attributes_class: Cloudflare::Types::ZeroTrustTunnelCloudflaredRouteAttributes,
      outputs: { id: :id },
      map: [:account_id, :network, :tunnel_id],
      map_present: [:comment, :virtual_network_id]
  end
  module Cloudflare
    include CloudflareZeroTrustTunnelCloudflaredRoute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
