# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZeroTrustGatewayCertificateAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute? :activate, T::Bool.optional
    attribute? :validity_period_days, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
