# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class MagicTransitSiteLanAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :site_id, T::String
    attribute? :bond_id, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :ha_link, T::Bool.optional
    attribute? :name, T::String.optional
    attribute? :nat, T::Hash.optional
    attribute? :physport, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :routed_subnets, T::Array.of(T::Hash).optional
    attribute? :static_addressing, T::Hash.optional
    attribute? :vlan_tag, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
