# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_waiting_room_event/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareWaitingRoomEvent
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_waiting_room_event,
      attributes_class: Cloudflare::Types::WaitingRoomEventAttributes,
      outputs: { id: :id },
      map: [:event_end_time, :event_start_time, :name, :waiting_room_id, :zone_id],
      map_present: [:custom_page_html, :description, :new_users_per_minute, :prequeue_start_time, :queueing_method, :session_duration, :total_active_users, :turnstile_action, :turnstile_mode],
      map_bool: [:disable_session_renewal, :shuffle_at_event_start, :suspended]
  end
  module Cloudflare
    include CloudflareWaitingRoomEvent
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
