# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ApiShieldSchemaAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :file, T::String
    attribute :kind, T::String
    attribute :zone_id, T::String
    attribute? :name, T::String.optional
    attribute? :schema_id, T::String.optional
    attribute? :validation_enabled, T::String.optional
  end
end
