# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_page_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflarePageRule
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_page_rule,
      attributes_class: Cloudflare::Types::PageRuleAttributes,
      outputs: { id: :id },
      map: [:actions, :target, :zone_id],
      map_present: [:priority, :status]
  end
  module Cloudflare
    include CloudflarePageRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
