# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class StreamLiveInputAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute? :default_creator, T::String.optional
    attribute? :delete_recording_after_days, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :enabled, T::Bool.optional
    attribute? :live_input_identifier, T::String.optional
    attribute? :meta, T::String.optional
    attribute? :recording, T::Hash.optional
  end
end
