# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_firewall_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareFirewallRule
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_firewall_rule,
      attributes_class: Cloudflare::Types::FirewallRuleAttributes,
      outputs: { id: :id },
      map: [:action, :filter, :zone_id]
  end
  module Cloudflare
    include CloudflareFirewallRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
