# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_custom_origin_trust_store infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_custom_origin_trust_store/ -t cloudflare://

control 'cloudflare_custom_origin_trust_store-exists' do
  impact 1.0
  title 'Manages a cloudflare_custom_origin_trust_store resource'
  desc 'Verify that the cloudflare_custom_origin_trust_store resource exists and has expected properties'

  describe cloudflare_custom_origin_trust_store(name: attribute('id')) do
    it { should exist }
    its('certificate') { should_not be_nil }
    its('zone_id') { should_not be_nil }
  end
end
