# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_pages_domain infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_pages_domain/ -t cloudflare://

control 'cloudflare_pages_domain-exists' do
  impact 1.0
  title 'Manages a cloudflare_pages_domain resource'
  desc 'Verify that the cloudflare_pages_domain resource exists and has expected properties'

  describe cloudflare_pages_domain(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('name') { should_not be_nil }
    its('project_name') { should_not be_nil }
  end
end
