# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zone_cache_reserve/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZoneCacheReserve
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zone_cache_reserve,
      attributes_class: Cloudflare::Types::ZoneCacheReserveAttributes,
      outputs: { id: :id },
      map: [:zone_id],
      map_present: [:value]
  end
  module Cloudflare
    include CloudflareZoneCacheReserve
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
