# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ConnectivityDirectoryServiceAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :host, T::Hash
    attribute :name, T::String
    attribute :type, T::String
    attribute? :http_port, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :https_port, (T::Coercible::Integer | T::Coercible::Float).optional
  end
end
