# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_list/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareList
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_list,
      attributes_class: Cloudflare::Types::ListAttributes,
      outputs: { id: :id },
      map: [:account_id, :kind, :name],
      map_present: [:description, :items]
  end
  module Cloudflare
    include CloudflareList
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
