# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class BotManagementAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :zone_id, T::String
    attribute? :ai_bots_protection, T::String.optional
    attribute? :auto_update_model, T::Bool.optional
    attribute? :bm_cookie_enabled, T::Bool.optional
    attribute? :cf_robots_variant, T::String.optional
    attribute? :crawler_protection, T::String.optional
    attribute? :enable_js, T::Bool.optional
    attribute? :fight_mode, T::Bool.optional
    attribute? :is_robots_txt_managed, T::Bool.optional
    attribute? :optimize_wordpress, T::Bool.optional
    attribute? :sbfm_definitely_automated, T::String.optional
    attribute? :sbfm_likely_automated, T::String.optional
    attribute? :sbfm_static_resource_protection, T::Bool.optional
    attribute? :sbfm_verified_bots, T::String.optional
    attribute? :suppress_session_score, T::Bool.optional
  end
end
