# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class R2CustomDomainAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :bucket_name, T::String
    attribute :domain, T::String
    attribute :enabled, T::Bool
    attribute :zone_id, T::String
    attribute? :ciphers, T::Array.of(T::String).optional
    attribute? :jurisdiction, T::String.optional
    attribute? :min_tls, T::String.optional
  end
end
