# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_account_member/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareAccountMember
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_account_member,
      attributes_class: Cloudflare::Types::AccountMemberAttributes,
      outputs: { id: :id },
      map: [:account_id, :email],
      map_present: [:policies, :roles, :status]
  end
  module Cloudflare
    include CloudflareAccountMember
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
