# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_zero_trust_access_mtls_certificate/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareZeroTrustAccessMtlsCertificate
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_zero_trust_access_mtls_certificate,
      attributes_class: Cloudflare::Types::ZeroTrustAccessMtlsCertificateAttributes,
      outputs: { id: :id },
      map: [:certificate, :name],
      map_present: [:account_id, :associated_hostnames, :zone_id]
  end
  module Cloudflare
    include CloudflareZeroTrustAccessMtlsCertificate
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
