# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_web3_hostname/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareWeb3Hostname
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_web3_hostname,
      attributes_class: Cloudflare::Types::Web3HostnameAttributes,
      outputs: { id: :id },
      map: [:name, :target, :zone_id],
      map_present: [:description, :dnslink]
  end
  module Cloudflare
    include CloudflareWeb3Hostname
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
