# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class RegistrarDomainAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :domain_name, T::String
    attribute? :auto_renew, T::Bool.optional
    attribute? :locked, T::Bool.optional
    attribute? :privacy, T::Bool.optional
  end
end
