# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_turnstile_widget/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareTurnstileWidget
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_turnstile_widget,
      attributes_class: Cloudflare::Types::TurnstileWidgetAttributes,
      outputs: { id: :id },
      map: [:account_id, :domains, :mode, :name],
      map_present: [:clearance_level, :region],
      map_bool: [:bot_fight_mode, :ephemeral_id, :offlabel]
  end
  module Cloudflare
    include CloudflareTurnstileWidget
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
