# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_filter/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareFilter
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_filter,
      attributes_class: Cloudflare::Types::FilterAttributes,
      outputs: { id: :id },
      map: [:body, :zone_id],
      map_present: [:description, :expression, :ref],
      map_bool: [:paused]
  end
  module Cloudflare
    include CloudflareFilter
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
