# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zero_trust_gateway_settings infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zero_trust_gateway_settings/ -t cloudflare://

control 'cloudflare_zero_trust_gateway_settings-exists' do
  impact 1.0
  title 'Manages a cloudflare_zero_trust_gateway_settings resource'
  desc 'Verify that the cloudflare_zero_trust_gateway_settings resource exists and has expected properties'

  describe cloudflare_zero_trust_gateway_settings(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
  end
end
