# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_magic_wan_gre_tunnel/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareMagicWanGreTunnel
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_magic_wan_gre_tunnel,
      attributes_class: Cloudflare::Types::MagicWanGreTunnelAttributes,
      outputs: { id: :id },
      map: [:account_id, :cloudflare_gre_endpoint, :customer_gre_endpoint, :interface_address, :name],
      map_present: [:bgp, :description, :health_check, :interface_address6, :mtu, :ttl],
      map_bool: [:automatic_return_routing]
  end
  module Cloudflare
    include CloudflareMagicWanGreTunnel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
