# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_dns_zone_transfers_peer infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_dns_zone_transfers_peer/ -t cloudflare://

control 'cloudflare_dns_zone_transfers_peer-exists' do
  impact 1.0
  title 'Manages a cloudflare_dns_zone_transfers_peer resource'
  desc 'Verify that the cloudflare_dns_zone_transfers_peer resource exists and has expected properties'

  describe cloudflare_dns_zone_transfers_peer(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('name') { should_not be_nil }
  end
end
