# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_zero_trust_access_key_configuration infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_zero_trust_access_key_configuration/ -t cloudflare://

control 'cloudflare_zero_trust_access_key_configuration-exists' do
  impact 1.0
  title 'Manages a cloudflare_zero_trust_access_key_configuration resource'
  desc 'Verify that the cloudflare_zero_trust_access_key_configuration resource exists and has expected properties'

  describe cloudflare_zero_trust_access_key_configuration(name: attribute('id')) do
    it { should exist }
    its('account_id') { should_not be_nil }
    its('key_rotation_interval_days') { should_not be_nil }
  end
end
