# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZeroTrustAccessServiceTokenAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :name, T::String
    attribute? :account_id, T::String.optional
    attribute? :client_secret_version, (T::Coercible::Integer | T::Coercible::Float).optional
    attribute? :duration, T::String.optional
    attribute? :previous_client_secret_expires_at, T::String.optional
    attribute? :zone_id, T::String.optional
  end
end
