# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/cloudflare_image/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module CloudflareImage
    include Pangea::Resources::ResourceBuilder

    define_resource :cloudflare_image,
      attributes_class: Cloudflare::Types::ImageAttributes,
      outputs: { id: :id },
      map: [:account_id, :id],
      map_present: [:creator, :file, :metadata, :url],
      map_bool: [:require_signed_urls]
  end
  module Cloudflare
    include CloudflareImage
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Cloudflare)
