# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class MagicTransitSiteAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :name, T::String
    attribute? :connector_id, T::String.optional
    attribute? :description, T::String.optional
    attribute? :ha_mode, T::Bool.optional
    attribute? :location, T::Hash.optional
    attribute? :secondary_connector_id, T::String.optional
  end
end
