# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_list_item resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareListItem do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', list_id: 'test-value' } }

  describe ':cloudflare_list_item' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'test')
        validate_required_attributes(config, [:account_id, :list_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_list_item('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_list_item)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_list_item('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_list_item.test.id}")
        expect(ref.created_on).to eq("${cloudflare_list_item.test.created_on}")
        expect(ref.modified_on).to eq("${cloudflare_list_item.test.modified_on}")
        expect(ref.operation_id).to eq("${cloudflare_list_item.test.operation_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_list_item', 'test')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('modified_on')
        expect(config).not_to have_key('operation_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ asn: 3.14, comment: 'test-value', hostname: { 'key1' => 'val1' }, ip: 'test-value', redirect: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_list_item', 'full')
        expect(config).to have_key('asn')
        expect(config).to have_key('comment')
        expect(config).to have_key('hostname')
        expect(config).to have_key('ip')
        expect(config).to have_key('redirect')
      end
    end

    context 'optional attributes' do
      it 'includes asn when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('opt', required_attrs.merge(asn: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'opt')
        expect(config).to have_key('asn')
      end

      it 'omits asn when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'minimal')
        expect(config).not_to have_key('asn')
      end
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes hostname when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('opt', required_attrs.merge(hostname: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'opt')
        expect(config).to have_key('hostname')
      end

      it 'omits hostname when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'minimal')
        expect(config).not_to have_key('hostname')
      end
      it 'includes ip when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('opt', required_attrs.merge(ip: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'opt')
        expect(config).to have_key('ip')
      end

      it 'omits ip when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'minimal')
        expect(config).not_to have_key('ip')
      end
      it 'includes redirect when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('opt', required_attrs.merge(redirect: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'opt')
        expect(config).to have_key('redirect')
      end

      it 'omits redirect when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_list_item', 'minimal')
        expect(config).not_to have_key('redirect')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_list_item', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['list_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_list_item('first', required_attrs)
        synth.cloudflare_list_item('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_list_item')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_list_item,
    method: :cloudflare_list_item,
    required_attrs: { account_id: 'test-value', list_id: 'test-value' },
    expected_outputs: [:id, :created_on, :modified_on, :operation_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
