# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_regional_tiered_cache resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareRegionalTieredCache do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { zone_id: 'test-value' } }

  describe ':cloudflare_regional_tiered_cache' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_regional_tiered_cache', 'test')
        validate_required_attributes(config, [:zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_regional_tiered_cache('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_regional_tiered_cache)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_regional_tiered_cache('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_regional_tiered_cache.test.id}")
        expect(ref.editable).to eq("${cloudflare_regional_tiered_cache.test.editable}")
        expect(ref.modified_on).to eq("${cloudflare_regional_tiered_cache.test.modified_on}")
        expect(ref.value).to eq("${cloudflare_regional_tiered_cache.test.value}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_regional_tiered_cache', 'test')
        expect(config).not_to have_key('editable')
        expect(config).not_to have_key('modified_on')
        expect(config).not_to have_key('value')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ value: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_regional_tiered_cache', 'full')
        expect(config).to have_key('value')
      end
    end

    context 'optional attributes' do
      it 'includes value when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('opt', required_attrs.merge(value: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_regional_tiered_cache', 'opt')
        expect(config).to have_key('value')
      end

      it 'omits value when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_regional_tiered_cache', 'minimal')
        expect(config).not_to have_key('value')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_regional_tiered_cache', 'typed')
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_regional_tiered_cache('first', required_attrs)
        synth.cloudflare_regional_tiered_cache('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_regional_tiered_cache')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_regional_tiered_cache,
    method: :cloudflare_regional_tiered_cache,
    required_attrs: { zone_id: 'test-value' },
    expected_outputs: [:id, :editable, :modified_on, :value],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
