# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_cloud_connector_rules resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareCloudConnectorRules do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { zone_id: 'test-value' } }

  describe ':cloudflare_cloud_connector_rules' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_cloud_connector_rules('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_cloud_connector_rules', 'test')
        validate_required_attributes(config, [:zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_cloud_connector_rules('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_cloud_connector_rules)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_cloud_connector_rules('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_cloud_connector_rules.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ rules: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_cloud_connector_rules('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_cloud_connector_rules', 'full')
        expect(config).to have_key('rules')
      end
    end

    context 'optional attributes' do
      it 'includes rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_cloud_connector_rules('opt', required_attrs.merge(rules: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_cloud_connector_rules', 'opt')
        expect(config).to have_key('rules')
      end

      it 'omits rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_cloud_connector_rules('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_cloud_connector_rules', 'minimal')
        expect(config).not_to have_key('rules')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_cloud_connector_rules('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_cloud_connector_rules', 'typed')
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_cloud_connector_rules('first', required_attrs)
        synth.cloudflare_cloud_connector_rules('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_cloud_connector_rules')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_cloud_connector_rules,
    method: :cloudflare_cloud_connector_rules,
    required_attrs: { zone_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
