# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zone_hold resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZoneHold do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { zone_id: 'test-value' } }

  describe ':cloudflare_zone_hold' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'test')
        validate_required_attributes(config, [:zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zone_hold('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zone_hold)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zone_hold('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zone_hold.test.id}")
        expect(ref.hold).to eq("${cloudflare_zone_hold.test.hold}")
        expect(ref.hold_after).to eq("${cloudflare_zone_hold.test.hold_after}")
        expect(ref.include_subdomains).to eq("${cloudflare_zone_hold.test.include_subdomains}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'test')
        expect(config).not_to have_key('hold')
        expect(config).not_to have_key('hold_after')
        expect(config).not_to have_key('include_subdomains')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ hold_after: 'test-value', include_subdomains: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'full')
        expect(config).to have_key('hold_after')
        expect(config).to have_key('include_subdomains')
      end
    end

    context 'optional attributes' do
      it 'includes hold_after when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('opt', required_attrs.merge(hold_after: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'opt')
        expect(config).to have_key('hold_after')
      end

      it 'omits hold_after when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'minimal')
        expect(config).not_to have_key('hold_after')
      end
      it 'includes include_subdomains when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('opt', required_attrs.merge(include_subdomains: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'opt')
        expect(config).to have_key('include_subdomains')
      end

      it 'omits include_subdomains when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'minimal')
        expect(config).not_to have_key('include_subdomains')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts include_subdomains=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(include_subdomains: val)
          synth.cloudflare_zone_hold("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zone_hold', "bool_#{val}")
          expect(config['include_subdomains']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zone_hold', 'typed')
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zone_hold('first', required_attrs)
        synth.cloudflare_zone_hold('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zone_hold')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zone_hold,
    method: :cloudflare_zone_hold,
    required_attrs: { zone_id: 'test-value' },
    expected_outputs: [:id, :hold, :hold_after, :include_subdomains],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:include_subdomains]
end
