# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_hostname_tls_setting resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareHostnameTlsSetting do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { hostname: 'test-value', setting_id: 'test-value', value: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_hostname_tls_setting' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_hostname_tls_setting('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_hostname_tls_setting', 'test')
        validate_required_attributes(config, [:hostname, :setting_id, :value, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_hostname_tls_setting('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_hostname_tls_setting)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_hostname_tls_setting('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_hostname_tls_setting.test.id}")
        expect(ref.created_at).to eq("${cloudflare_hostname_tls_setting.test.created_at}")
        expect(ref.status).to eq("${cloudflare_hostname_tls_setting.test.status}")
        expect(ref.updated_at).to eq("${cloudflare_hostname_tls_setting.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_hostname_tls_setting('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_hostname_tls_setting', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_hostname_tls_setting('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_hostname_tls_setting', 'typed')
        expect(config['hostname']).to be_a(String)
        expect(config['setting_id']).to be_a(String)
        expect(config['value']).to be_a(Object)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_hostname_tls_setting('first', required_attrs)
        synth.cloudflare_hostname_tls_setting('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_hostname_tls_setting')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_hostname_tls_setting,
    method: :cloudflare_hostname_tls_setting,
    required_attrs: { hostname: 'test-value', setting_id: 'test-value', value: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :created_at, :status, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
