# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_pages_project resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflarePagesProject do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', name: 'test-value', production_branch: 'test-value' } }

  describe ':cloudflare_pages_project' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'test')
        validate_required_attributes(config, [:account_id, :name, :production_branch])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_pages_project('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_pages_project)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_pages_project('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_pages_project.test.id}")
        expect(ref.build_config).to eq("${cloudflare_pages_project.test.build_config}")
        expect(ref.canonical_deployment).to eq("${cloudflare_pages_project.test.canonical_deployment}")
        expect(ref.created_on).to eq("${cloudflare_pages_project.test.created_on}")
        expect(ref.deployment_configs).to eq("${cloudflare_pages_project.test.deployment_configs}")
        expect(ref.domains).to eq("${cloudflare_pages_project.test.domains}")
        expect(ref.framework).to eq("${cloudflare_pages_project.test.framework}")
        expect(ref.framework_version).to eq("${cloudflare_pages_project.test.framework_version}")
        expect(ref.latest_deployment).to eq("${cloudflare_pages_project.test.latest_deployment}")
        expect(ref.preview_script_name).to eq("${cloudflare_pages_project.test.preview_script_name}")
        expect(ref.production_script_name).to eq("${cloudflare_pages_project.test.production_script_name}")
        expect(ref.subdomain).to eq("${cloudflare_pages_project.test.subdomain}")
        expect(ref.uses_functions).to eq("${cloudflare_pages_project.test.uses_functions}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_pages_project', 'test')
        expect(config).not_to have_key('build_config')
        expect(config).not_to have_key('canonical_deployment')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('deployment_configs')
        expect(config).not_to have_key('domains')
        expect(config).not_to have_key('framework')
        expect(config).not_to have_key('framework_version')
        expect(config).not_to have_key('latest_deployment')
        expect(config).not_to have_key('preview_script_name')
        expect(config).not_to have_key('production_script_name')
        expect(config).not_to have_key('subdomain')
        expect(config).not_to have_key('uses_functions')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ build_config: { 'key1' => 'val1' }, deployment_configs: { 'key1' => 'val1' }, source: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_pages_project', 'full')
        expect(config).to have_key('build_config')
        expect(config).to have_key('deployment_configs')
        expect(config).to have_key('source')
      end
    end

    context 'optional attributes' do
      it 'includes build_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('opt', required_attrs.merge(build_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'opt')
        expect(config).to have_key('build_config')
      end

      it 'omits build_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'minimal')
        expect(config).not_to have_key('build_config')
      end
      it 'includes deployment_configs when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('opt', required_attrs.merge(deployment_configs: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'opt')
        expect(config).to have_key('deployment_configs')
      end

      it 'omits deployment_configs when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'minimal')
        expect(config).not_to have_key('deployment_configs')
      end
      it 'includes source when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('opt', required_attrs.merge(source: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'opt')
        expect(config).to have_key('source')
      end

      it 'omits source when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_pages_project', 'minimal')
        expect(config).not_to have_key('source')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_pages_project', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['production_branch']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_pages_project('first', required_attrs)
        synth.cloudflare_pages_project('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_pages_project')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_pages_project,
    method: :cloudflare_pages_project,
    required_attrs: { account_id: 'test-value', name: 'test-value', production_branch: 'test-value' },
    expected_outputs: [:id, :build_config, :canonical_deployment, :created_on, :deployment_configs, :domains, :framework, :framework_version, :latest_deployment, :preview_script_name, :production_script_name, :subdomain, :uses_functions],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
