# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_gateway_proxy_endpoint resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustGatewayProxyEndpoint do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_gateway_proxy_endpoint' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'test')
        validate_required_attributes(config, [:account_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_gateway_proxy_endpoint('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_gateway_proxy_endpoint)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_gateway_proxy_endpoint('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_gateway_proxy_endpoint.test.id}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_gateway_proxy_endpoint.test.created_at}")
        expect(ref.kind).to eq("${cloudflare_zero_trust_gateway_proxy_endpoint.test.kind}")
        expect(ref.subdomain).to eq("${cloudflare_zero_trust_gateway_proxy_endpoint.test.subdomain}")
        expect(ref.updated_at).to eq("${cloudflare_zero_trust_gateway_proxy_endpoint.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('kind')
        expect(config).not_to have_key('subdomain')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ips: ['test-value'], kind: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'full')
        expect(config).to have_key('ips')
        expect(config).to have_key('kind')
      end
    end

    context 'optional attributes' do
      it 'includes ips when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('opt', required_attrs.merge(ips: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'opt')
        expect(config).to have_key('ips')
      end

      it 'omits ips when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'minimal')
        expect(config).not_to have_key('ips')
      end
      it 'includes kind when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('opt', required_attrs.merge(kind: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'opt')
        expect(config).to have_key('kind')
      end

      it 'omits kind when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'minimal')
        expect(config).not_to have_key('kind')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_proxy_endpoint', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('first', required_attrs)
        synth.cloudflare_zero_trust_gateway_proxy_endpoint('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_gateway_proxy_endpoint')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_gateway_proxy_endpoint,
    method: :cloudflare_zero_trust_gateway_proxy_endpoint,
    required_attrs: { account_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :created_at, :kind, :subdomain, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
