# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_client_certificate resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareClientCertificate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { csr: 'test-value', validity_days: 3.14, zone_id: 'test-value' } }

  describe ':cloudflare_client_certificate' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_client_certificate', 'test')
        validate_required_attributes(config, [:csr, :validity_days, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_client_certificate('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_client_certificate)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_client_certificate('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_client_certificate.test.id}")
        expect(ref.certificate).to eq("${cloudflare_client_certificate.test.certificate}")
        expect(ref.certificate_authority).to eq("${cloudflare_client_certificate.test.certificate_authority}")
        expect(ref.common_name).to eq("${cloudflare_client_certificate.test.common_name}")
        expect(ref.country).to eq("${cloudflare_client_certificate.test.country}")
        expect(ref.expires_on).to eq("${cloudflare_client_certificate.test.expires_on}")
        expect(ref.fingerprint_sha256).to eq("${cloudflare_client_certificate.test.fingerprint_sha256}")
        expect(ref.issued_on).to eq("${cloudflare_client_certificate.test.issued_on}")
        expect(ref.location).to eq("${cloudflare_client_certificate.test.location}")
        expect(ref.organization).to eq("${cloudflare_client_certificate.test.organization}")
        expect(ref.organizational_unit).to eq("${cloudflare_client_certificate.test.organizational_unit}")
        expect(ref.serial_number).to eq("${cloudflare_client_certificate.test.serial_number}")
        expect(ref.signature).to eq("${cloudflare_client_certificate.test.signature}")
        expect(ref.ski).to eq("${cloudflare_client_certificate.test.ski}")
        expect(ref.state).to eq("${cloudflare_client_certificate.test.state}")
        expect(ref.status).to eq("${cloudflare_client_certificate.test.status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_client_certificate', 'test')
        expect(config).not_to have_key('certificate')
        expect(config).not_to have_key('certificate_authority')
        expect(config).not_to have_key('common_name')
        expect(config).not_to have_key('country')
        expect(config).not_to have_key('expires_on')
        expect(config).not_to have_key('fingerprint_sha256')
        expect(config).not_to have_key('issued_on')
        expect(config).not_to have_key('location')
        expect(config).not_to have_key('organization')
        expect(config).not_to have_key('organizational_unit')
        expect(config).not_to have_key('serial_number')
        expect(config).not_to have_key('signature')
        expect(config).not_to have_key('ski')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ reactivate: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_client_certificate', 'full')
        expect(config).to have_key('reactivate')
      end
    end

    context 'optional attributes' do
      it 'includes reactivate when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('opt', required_attrs.merge(reactivate: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_client_certificate', 'opt')
        expect(config).to have_key('reactivate')
      end

      it 'omits reactivate when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_client_certificate', 'minimal')
        expect(config).not_to have_key('reactivate')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts reactivate=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(reactivate: val)
          synth.cloudflare_client_certificate("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_client_certificate', "bool_#{val}")
          expect(config['reactivate']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_client_certificate', 'typed')
        expect(config['csr']).to be_a(String)
        expect(config['validity_days']).to be_a(Float)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_client_certificate('first', required_attrs)
        synth.cloudflare_client_certificate('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_client_certificate')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_client_certificate,
    method: :cloudflare_client_certificate,
    required_attrs: { csr: 'test-value', validity_days: 3.14, zone_id: 'test-value' },
    expected_outputs: [:id, :certificate, :certificate_authority, :common_name, :country, :expires_on, :fingerprint_sha256, :issued_on, :location, :organization, :organizational_unit, :serial_number, :signature, :ski, :state, :status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:reactivate]
end
