# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_dlp_custom_entry resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustDlpCustomEntry do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', enabled: true, name: 'test-value', pattern: { 'key1' => 'val1' } } }

  describe ':cloudflare_zero_trust_dlp_custom_entry' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'test')
        validate_required_attributes(config, [:account_id, :enabled, :name, :pattern])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dlp_custom_entry('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_dlp_custom_entry)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dlp_custom_entry('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.id}")
        expect(ref.case_sensitive).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.case_sensitive}")
        expect(ref.confidence).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.confidence}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.created_at}")
        expect(ref.profiles).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.profiles}")
        expect(ref.secret).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.secret}")
        expect(ref.type).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.type}")
        expect(ref.updated_at).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.updated_at}")
        expect(ref.upload_status).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.upload_status}")
        expect(ref.variant).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.variant}")
        expect(ref.word_list).to eq("${cloudflare_zero_trust_dlp_custom_entry.test.word_list}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'test')
        expect(config).not_to have_key('case_sensitive')
        expect(config).not_to have_key('confidence')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('profiles')
        expect(config).not_to have_key('secret')
        expect(config).not_to have_key('type')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('upload_status')
        expect(config).not_to have_key('variant')
        expect(config).not_to have_key('word_list')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', profile_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('profile_id')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes profile_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('opt', required_attrs.merge(profile_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'opt')
        expect(config).to have_key('profile_id')
      end

      it 'omits profile_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'minimal')
        expect(config).not_to have_key('profile_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.cloudflare_zero_trust_dlp_custom_entry("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_entry', 'typed')
        expect(config['account_id']).to be_a(String)
        expect([true, false]).to include(config['enabled'])
        expect(config['name']).to be_a(String)
        expect(config['pattern']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_entry('first', required_attrs)
        synth.cloudflare_zero_trust_dlp_custom_entry('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_dlp_custom_entry')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_dlp_custom_entry,
    method: :cloudflare_zero_trust_dlp_custom_entry,
    required_attrs: { account_id: 'test-value', enabled: true, name: 'test-value', pattern: { 'key1' => 'val1' } },
    expected_outputs: [:id, :case_sensitive, :confidence, :created_at, :profiles, :secret, :type, :updated_at, :upload_status, :variant, :word_list],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
