# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_bot_management resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareBotManagement do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { zone_id: 'test-value' } }

  describe ':cloudflare_bot_management' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'test')
        validate_required_attributes(config, [:zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_bot_management('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_bot_management)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_bot_management('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_bot_management.test.id}")
        expect(ref.ai_bots_protection).to eq("${cloudflare_bot_management.test.ai_bots_protection}")
        expect(ref.auto_update_model).to eq("${cloudflare_bot_management.test.auto_update_model}")
        expect(ref.bm_cookie_enabled).to eq("${cloudflare_bot_management.test.bm_cookie_enabled}")
        expect(ref.cf_robots_variant).to eq("${cloudflare_bot_management.test.cf_robots_variant}")
        expect(ref.crawler_protection).to eq("${cloudflare_bot_management.test.crawler_protection}")
        expect(ref.enable_js).to eq("${cloudflare_bot_management.test.enable_js}")
        expect(ref.fight_mode).to eq("${cloudflare_bot_management.test.fight_mode}")
        expect(ref.is_robots_txt_managed).to eq("${cloudflare_bot_management.test.is_robots_txt_managed}")
        expect(ref.optimize_wordpress).to eq("${cloudflare_bot_management.test.optimize_wordpress}")
        expect(ref.sbfm_definitely_automated).to eq("${cloudflare_bot_management.test.sbfm_definitely_automated}")
        expect(ref.sbfm_likely_automated).to eq("${cloudflare_bot_management.test.sbfm_likely_automated}")
        expect(ref.sbfm_static_resource_protection).to eq("${cloudflare_bot_management.test.sbfm_static_resource_protection}")
        expect(ref.sbfm_verified_bots).to eq("${cloudflare_bot_management.test.sbfm_verified_bots}")
        expect(ref.stale_zone_configuration).to eq("${cloudflare_bot_management.test.stale_zone_configuration}")
        expect(ref.suppress_session_score).to eq("${cloudflare_bot_management.test.suppress_session_score}")
        expect(ref.using_latest_model).to eq("${cloudflare_bot_management.test.using_latest_model}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_bot_management', 'test')
        expect(config).not_to have_key('ai_bots_protection')
        expect(config).not_to have_key('auto_update_model')
        expect(config).not_to have_key('bm_cookie_enabled')
        expect(config).not_to have_key('cf_robots_variant')
        expect(config).not_to have_key('crawler_protection')
        expect(config).not_to have_key('enable_js')
        expect(config).not_to have_key('fight_mode')
        expect(config).not_to have_key('is_robots_txt_managed')
        expect(config).not_to have_key('optimize_wordpress')
        expect(config).not_to have_key('sbfm_definitely_automated')
        expect(config).not_to have_key('sbfm_likely_automated')
        expect(config).not_to have_key('sbfm_static_resource_protection')
        expect(config).not_to have_key('sbfm_verified_bots')
        expect(config).not_to have_key('stale_zone_configuration')
        expect(config).not_to have_key('suppress_session_score')
        expect(config).not_to have_key('using_latest_model')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ai_bots_protection: 'test-value', auto_update_model: true, bm_cookie_enabled: true, cf_robots_variant: 'test-value', crawler_protection: 'test-value', enable_js: true, fight_mode: true, is_robots_txt_managed: true, optimize_wordpress: true, sbfm_definitely_automated: 'test-value', sbfm_likely_automated: 'test-value', sbfm_static_resource_protection: true, sbfm_verified_bots: 'test-value', suppress_session_score: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_bot_management', 'full')
        expect(config).to have_key('ai_bots_protection')
        expect(config).to have_key('auto_update_model')
        expect(config).to have_key('bm_cookie_enabled')
        expect(config).to have_key('cf_robots_variant')
        expect(config).to have_key('crawler_protection')
        expect(config).to have_key('enable_js')
        expect(config).to have_key('fight_mode')
        expect(config).to have_key('is_robots_txt_managed')
        expect(config).to have_key('optimize_wordpress')
        expect(config).to have_key('sbfm_definitely_automated')
        expect(config).to have_key('sbfm_likely_automated')
        expect(config).to have_key('sbfm_static_resource_protection')
        expect(config).to have_key('sbfm_verified_bots')
        expect(config).to have_key('suppress_session_score')
      end
    end

    context 'optional attributes' do
      it 'includes ai_bots_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(ai_bots_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('ai_bots_protection')
      end

      it 'omits ai_bots_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('ai_bots_protection')
      end
      it 'includes auto_update_model when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(auto_update_model: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('auto_update_model')
      end

      it 'omits auto_update_model when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('auto_update_model')
      end
      it 'includes bm_cookie_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(bm_cookie_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('bm_cookie_enabled')
      end

      it 'omits bm_cookie_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('bm_cookie_enabled')
      end
      it 'includes cf_robots_variant when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(cf_robots_variant: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('cf_robots_variant')
      end

      it 'omits cf_robots_variant when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('cf_robots_variant')
      end
      it 'includes crawler_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(crawler_protection: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('crawler_protection')
      end

      it 'omits crawler_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('crawler_protection')
      end
      it 'includes enable_js when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(enable_js: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('enable_js')
      end

      it 'omits enable_js when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('enable_js')
      end
      it 'includes fight_mode when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(fight_mode: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('fight_mode')
      end

      it 'omits fight_mode when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('fight_mode')
      end
      it 'includes is_robots_txt_managed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(is_robots_txt_managed: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('is_robots_txt_managed')
      end

      it 'omits is_robots_txt_managed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('is_robots_txt_managed')
      end
      it 'includes optimize_wordpress when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(optimize_wordpress: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('optimize_wordpress')
      end

      it 'omits optimize_wordpress when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('optimize_wordpress')
      end
      it 'includes sbfm_definitely_automated when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(sbfm_definitely_automated: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('sbfm_definitely_automated')
      end

      it 'omits sbfm_definitely_automated when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('sbfm_definitely_automated')
      end
      it 'includes sbfm_likely_automated when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(sbfm_likely_automated: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('sbfm_likely_automated')
      end

      it 'omits sbfm_likely_automated when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('sbfm_likely_automated')
      end
      it 'includes sbfm_static_resource_protection when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(sbfm_static_resource_protection: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('sbfm_static_resource_protection')
      end

      it 'omits sbfm_static_resource_protection when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('sbfm_static_resource_protection')
      end
      it 'includes sbfm_verified_bots when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(sbfm_verified_bots: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('sbfm_verified_bots')
      end

      it 'omits sbfm_verified_bots when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('sbfm_verified_bots')
      end
      it 'includes suppress_session_score when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('opt', required_attrs.merge(suppress_session_score: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'opt')
        expect(config).to have_key('suppress_session_score')
      end

      it 'omits suppress_session_score when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_bot_management', 'minimal')
        expect(config).not_to have_key('suppress_session_score')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts auto_update_model=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(auto_update_model: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['auto_update_model']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts bm_cookie_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(bm_cookie_enabled: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['bm_cookie_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts enable_js=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_js: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['enable_js']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts fight_mode=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(fight_mode: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['fight_mode']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_robots_txt_managed=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_robots_txt_managed: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['is_robots_txt_managed']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts optimize_wordpress=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(optimize_wordpress: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['optimize_wordpress']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts sbfm_static_resource_protection=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(sbfm_static_resource_protection: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['sbfm_static_resource_protection']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts suppress_session_score=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(suppress_session_score: val)
          synth.cloudflare_bot_management("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_bot_management', "bool_#{val}")
          expect(config['suppress_session_score']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_bot_management', 'typed')
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_bot_management('first', required_attrs)
        synth.cloudflare_bot_management('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_bot_management')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_bot_management,
    method: :cloudflare_bot_management,
    required_attrs: { zone_id: 'test-value' },
    expected_outputs: [:id, :ai_bots_protection, :auto_update_model, :bm_cookie_enabled, :cf_robots_variant, :crawler_protection, :enable_js, :fight_mode, :is_robots_txt_managed, :optimize_wordpress, :sbfm_definitely_automated, :sbfm_likely_automated, :sbfm_static_resource_protection, :sbfm_verified_bots, :stale_zone_configuration, :suppress_session_score, :using_latest_model],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:auto_update_model, :bm_cookie_enabled, :enable_js, :fight_mode, :is_robots_txt_managed, :optimize_wordpress, :sbfm_static_resource_protection, :suppress_session_score]
end
