# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_account resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareAccount do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':cloudflare_account' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_account', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_account('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_account)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_account('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_account.test.id}")
        expect(ref.created_on).to eq("${cloudflare_account.test.created_on}")
        expect(ref.managed_by).to eq("${cloudflare_account.test.managed_by}")
        expect(ref.settings).to eq("${cloudflare_account.test.settings}")
        expect(ref.type).to eq("${cloudflare_account.test.type}")
        expect(ref.unit).to eq("${cloudflare_account.test.unit}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_account', 'test')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('managed_by')
        expect(config).not_to have_key('settings')
        expect(config).not_to have_key('type')
        expect(config).not_to have_key('unit')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ managed_by: { 'key1' => 'val1' }, settings: { 'key1' => 'val1' }, type: 'test-value', unit: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_account', 'full')
        expect(config).to have_key('managed_by')
        expect(config).to have_key('settings')
        expect(config).to have_key('type')
        expect(config).to have_key('unit')
      end
    end

    context 'optional attributes' do
      it 'includes managed_by when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('opt', required_attrs.merge(managed_by: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'opt')
        expect(config).to have_key('managed_by')
      end

      it 'omits managed_by when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'minimal')
        expect(config).not_to have_key('managed_by')
      end
      it 'includes settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('opt', required_attrs.merge(settings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'opt')
        expect(config).to have_key('settings')
      end

      it 'omits settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'minimal')
        expect(config).not_to have_key('settings')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'minimal')
        expect(config).not_to have_key('type')
      end
      it 'includes unit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('opt', required_attrs.merge(unit: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'opt')
        expect(config).to have_key('unit')
      end

      it 'omits unit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account', 'minimal')
        expect(config).not_to have_key('unit')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_account', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account('first', required_attrs)
        synth.cloudflare_account('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_account')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_account,
    method: :cloudflare_account,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :created_on, :managed_by, :settings, :type, :unit],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
