# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_ruleset resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareRuleset do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { kind: 'test-value', name: 'test-value', phase: 'test-value' } }

  describe ':cloudflare_ruleset' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'test')
        validate_required_attributes(config, [:kind, :name, :phase])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_ruleset('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_ruleset)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_ruleset('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_ruleset.test.id}")
        expect(ref.description).to eq("${cloudflare_ruleset.test.description}")
        expect(ref.last_updated).to eq("${cloudflare_ruleset.test.last_updated}")
        expect(ref.rules).to eq("${cloudflare_ruleset.test.rules}")
        expect(ref.version).to eq("${cloudflare_ruleset.test.version}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_ruleset', 'test')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('last_updated')
        expect(config).not_to have_key('rules')
        expect(config).not_to have_key('version')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_id: 'test-value', description: 'test-value', rules: [{ 'key1' => 'val1' }], zone_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_ruleset', 'full')
        expect(config).to have_key('account_id')
        expect(config).to have_key('description')
        expect(config).to have_key('rules')
        expect(config).to have_key('zone_id')
      end
    end

    context 'optional attributes' do
      it 'includes account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('opt', required_attrs.merge(account_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'opt')
        expect(config).to have_key('account_id')
      end

      it 'omits account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'minimal')
        expect(config).not_to have_key('account_id')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('opt', required_attrs.merge(rules: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'opt')
        expect(config).to have_key('rules')
      end

      it 'omits rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'minimal')
        expect(config).not_to have_key('rules')
      end
      it 'includes zone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('opt', required_attrs.merge(zone_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'opt')
        expect(config).to have_key('zone_id')
      end

      it 'omits zone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_ruleset', 'minimal')
        expect(config).not_to have_key('zone_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_ruleset', 'typed')
        expect(config['kind']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['phase']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_ruleset('first', required_attrs)
        synth.cloudflare_ruleset('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_ruleset')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_ruleset,
    method: :cloudflare_ruleset,
    required_attrs: { kind: 'test-value', name: 'test-value', phase: 'test-value' },
    expected_outputs: [:id, :description, :last_updated, :rules, :version],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
