# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_dns_zone_transfers_outgoing resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareDnsZoneTransfersOutgoing do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', peers: ['test-value'], zone_id: 'test-value' } }

  describe ':cloudflare_dns_zone_transfers_outgoing' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_zone_transfers_outgoing('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_dns_zone_transfers_outgoing', 'test')
        validate_required_attributes(config, [:name, :peers, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_dns_zone_transfers_outgoing('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_dns_zone_transfers_outgoing)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_dns_zone_transfers_outgoing('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_dns_zone_transfers_outgoing.test.id}")
        expect(ref.checked_time).to eq("${cloudflare_dns_zone_transfers_outgoing.test.checked_time}")
        expect(ref.created_time).to eq("${cloudflare_dns_zone_transfers_outgoing.test.created_time}")
        expect(ref.last_transferred_time).to eq("${cloudflare_dns_zone_transfers_outgoing.test.last_transferred_time}")
        expect(ref.soa_serial).to eq("${cloudflare_dns_zone_transfers_outgoing.test.soa_serial}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_zone_transfers_outgoing('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_dns_zone_transfers_outgoing', 'test')
        expect(config).not_to have_key('checked_time')
        expect(config).not_to have_key('created_time')
        expect(config).not_to have_key('last_transferred_time')
        expect(config).not_to have_key('soa_serial')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_zone_transfers_outgoing('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_dns_zone_transfers_outgoing', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['peers']).to be_a(Array)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_zone_transfers_outgoing('first', required_attrs)
        synth.cloudflare_dns_zone_transfers_outgoing('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_dns_zone_transfers_outgoing')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_dns_zone_transfers_outgoing,
    method: :cloudflare_dns_zone_transfers_outgoing,
    required_attrs: { name: 'test-value', peers: ['test-value'], zone_id: 'test-value' },
    expected_outputs: [:id, :checked_time, :created_time, :last_transferred_time, :soa_serial],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
