# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_workers_custom_domain resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareWorkersCustomDomain do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', hostname: 'test-value', service: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_workers_custom_domain' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_workers_custom_domain', 'test')
        validate_required_attributes(config, [:account_id, :hostname, :service, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_workers_custom_domain('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_workers_custom_domain)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_workers_custom_domain('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_workers_custom_domain.test.id}")
        expect(ref.zone_name).to eq("${cloudflare_workers_custom_domain.test.zone_name}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_workers_custom_domain', 'test')
        expect(config).not_to have_key('zone_name')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ environment: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_workers_custom_domain', 'full')
        expect(config).to have_key('environment')
      end
    end

    context 'optional attributes' do
      it 'includes environment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('opt', required_attrs.merge(environment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_workers_custom_domain', 'opt')
        expect(config).to have_key('environment')
      end

      it 'omits environment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_workers_custom_domain', 'minimal')
        expect(config).not_to have_key('environment')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_workers_custom_domain', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['hostname']).to be_a(String)
        expect(config['service']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_workers_custom_domain('first', required_attrs)
        synth.cloudflare_workers_custom_domain('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_workers_custom_domain')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_workers_custom_domain,
    method: :cloudflare_workers_custom_domain,
    required_attrs: { account_id: 'test-value', hostname: 'test-value', service: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :zone_name],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
