# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_api_shield_operation resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareApiShieldOperation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { endpoint: 'test-value', host: 'test-value', method: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_api_shield_operation' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_operation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_api_shield_operation', 'test')
        validate_required_attributes(config, [:endpoint, :host, :method, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_api_shield_operation('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_api_shield_operation)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_api_shield_operation('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_api_shield_operation.test.id}")
        expect(ref.features).to eq("${cloudflare_api_shield_operation.test.features}")
        expect(ref.last_updated).to eq("${cloudflare_api_shield_operation.test.last_updated}")
        expect(ref.operation_id).to eq("${cloudflare_api_shield_operation.test.operation_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_operation('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_api_shield_operation', 'test')
        expect(config).not_to have_key('features')
        expect(config).not_to have_key('last_updated')
        expect(config).not_to have_key('operation_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_operation('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_api_shield_operation', 'typed')
        expect(config['endpoint']).to be_a(String)
        expect(config['host']).to be_a(String)
        expect(config['method']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_operation('first', required_attrs)
        synth.cloudflare_api_shield_operation('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_api_shield_operation')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_api_shield_operation,
    method: :cloudflare_api_shield_operation,
    required_attrs: { endpoint: 'test-value', host: 'test-value', method: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :features, :last_updated, :operation_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
