# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_organization_profile resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareOrganizationProfile do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { business_address: 'test-value', business_email: 'test-value', business_name: 'test-value', business_phone: 'test-value', external_metadata: 'test-value', organization_id: 'test-value' } }

  describe ':cloudflare_organization_profile' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_organization_profile('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_organization_profile', 'test')
        validate_required_attributes(config, [:business_address, :business_email, :business_name, :business_phone, :external_metadata, :organization_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_organization_profile('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_organization_profile)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_organization_profile('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_organization_profile.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_organization_profile('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_organization_profile', 'typed')
        expect(config['business_address']).to be_a(String)
        expect(config['business_email']).to be_a(String)
        expect(config['business_name']).to be_a(String)
        expect(config['business_phone']).to be_a(String)
        expect(config['external_metadata']).to be_a(String)
        expect(config['organization_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_organization_profile('first', required_attrs)
        synth.cloudflare_organization_profile('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_organization_profile')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_organization_profile,
    method: :cloudflare_organization_profile,
    required_attrs: { business_address: 'test-value', business_email: 'test-value', business_name: 'test-value', business_phone: 'test-value', external_metadata: 'test-value', organization_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
