# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_snippet resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareSnippet do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { files: [{ 'key1' => 'val1' }], metadata: { 'key1' => 'val1' }, snippet_name: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_snippet' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_snippet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_snippet', 'test')
        validate_required_attributes(config, [:files, :metadata, :snippet_name, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_snippet('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_snippet)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_snippet('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_snippet.test.id}")
        expect(ref.created_on).to eq("${cloudflare_snippet.test.created_on}")
        expect(ref.modified_on).to eq("${cloudflare_snippet.test.modified_on}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_snippet('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_snippet', 'test')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('modified_on')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_snippet('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_snippet', 'typed')
        expect(config['files']).to be_a(Array)
        expect(config['metadata']).to be_a(Hash)
        expect(config['snippet_name']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_snippet('first', required_attrs)
        synth.cloudflare_snippet('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_snippet')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_snippet,
    method: :cloudflare_snippet,
    required_attrs: { files: [{ 'key1' => 'val1' }], metadata: { 'key1' => 'val1' }, snippet_name: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :created_on, :modified_on],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
