# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_tunnel_cloudflared_route resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustTunnelCloudflaredRoute do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', network: 'test-value', tunnel_id: 'test-value' } }

  describe ':cloudflare_zero_trust_tunnel_cloudflared_route' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'test')
        validate_required_attributes(config, [:account_id, :network, :tunnel_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_tunnel_cloudflared_route('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_tunnel_cloudflared_route)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_tunnel_cloudflared_route('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_tunnel_cloudflared_route.test.id}")
        expect(ref.comment).to eq("${cloudflare_zero_trust_tunnel_cloudflared_route.test.comment}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_tunnel_cloudflared_route.test.created_at}")
        expect(ref.deleted_at).to eq("${cloudflare_zero_trust_tunnel_cloudflared_route.test.deleted_at}")
        expect(ref.virtual_network_id).to eq("${cloudflare_zero_trust_tunnel_cloudflared_route.test.virtual_network_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'test')
        expect(config).not_to have_key('comment')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('deleted_at')
        expect(config).not_to have_key('virtual_network_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ comment: 'test-value', virtual_network_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'full')
        expect(config).to have_key('comment')
        expect(config).to have_key('virtual_network_id')
      end
    end

    context 'optional attributes' do
      it 'includes comment when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('opt', required_attrs.merge(comment: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'opt')
        expect(config).to have_key('comment')
      end

      it 'omits comment when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'minimal')
        expect(config).not_to have_key('comment')
      end
      it 'includes virtual_network_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('opt', required_attrs.merge(virtual_network_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'opt')
        expect(config).to have_key('virtual_network_id')
      end

      it 'omits virtual_network_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'minimal')
        expect(config).not_to have_key('virtual_network_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared_route', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['network']).to be_a(String)
        expect(config['tunnel_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('first', required_attrs)
        synth.cloudflare_zero_trust_tunnel_cloudflared_route('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_tunnel_cloudflared_route')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_tunnel_cloudflared_route,
    method: :cloudflare_zero_trust_tunnel_cloudflared_route,
    required_attrs: { account_id: 'test-value', network: 'test-value', tunnel_id: 'test-value' },
    expected_outputs: [:id, :comment, :created_at, :deleted_at, :virtual_network_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
