# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_custom_pages resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareCustomPages do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { identifier: 'test-value', state: 'test-value' } }

  describe ':cloudflare_custom_pages' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'test')
        validate_required_attributes(config, [:identifier, :state])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_custom_pages('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_custom_pages)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_custom_pages('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_custom_pages.test.id}")
        expect(ref.created_on).to eq("${cloudflare_custom_pages.test.created_on}")
        expect(ref.description).to eq("${cloudflare_custom_pages.test.description}")
        expect(ref.modified_on).to eq("${cloudflare_custom_pages.test.modified_on}")
        expect(ref.preview_target).to eq("${cloudflare_custom_pages.test.preview_target}")
        expect(ref.required_tokens).to eq("${cloudflare_custom_pages.test.required_tokens}")
        expect(ref.url).to eq("${cloudflare_custom_pages.test.url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'test')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('modified_on')
        expect(config).not_to have_key('preview_target')
        expect(config).not_to have_key('required_tokens')
        expect(config).not_to have_key('url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_id: 'test-value', url: 'test-value', zone_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'full')
        expect(config).to have_key('account_id')
        expect(config).to have_key('url')
        expect(config).to have_key('zone_id')
      end
    end

    context 'optional attributes' do
      it 'includes account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('opt', required_attrs.merge(account_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'opt')
        expect(config).to have_key('account_id')
      end

      it 'omits account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'minimal')
        expect(config).not_to have_key('account_id')
      end
      it 'includes url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('opt', required_attrs.merge(url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'opt')
        expect(config).to have_key('url')
      end

      it 'omits url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'minimal')
        expect(config).not_to have_key('url')
      end
      it 'includes zone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('opt', required_attrs.merge(zone_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'opt')
        expect(config).to have_key('zone_id')
      end

      it 'omits zone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'minimal')
        expect(config).not_to have_key('zone_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_pages', 'typed')
        expect(config['identifier']).to be_a(String)
        expect(config['state']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_pages('first', required_attrs)
        synth.cloudflare_custom_pages('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_custom_pages')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_custom_pages,
    method: :cloudflare_custom_pages,
    required_attrs: { identifier: 'test-value', state: 'test-value' },
    expected_outputs: [:id, :created_on, :description, :modified_on, :preview_target, :required_tokens, :url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
