# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_calls_sfu_app resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareCallsSfuApp do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value' } }

  describe ':cloudflare_calls_sfu_app' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'test')
        validate_required_attributes(config, [:account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_calls_sfu_app('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_calls_sfu_app)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_calls_sfu_app('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_calls_sfu_app.test.id}")
        expect(ref.created).to eq("${cloudflare_calls_sfu_app.test.created}")
        expect(ref.modified).to eq("${cloudflare_calls_sfu_app.test.modified}")
        expect(ref.name).to eq("${cloudflare_calls_sfu_app.test.name}")
        expect(ref.secret).to eq("${cloudflare_calls_sfu_app.test.secret}")
        expect(ref.uid).to eq("${cloudflare_calls_sfu_app.test.uid}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'test')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('modified')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('secret')
        expect(config).not_to have_key('uid')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ app_id: 'test-value', name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'full')
        expect(config).to have_key('app_id')
        expect(config).to have_key('name')
      end
    end

    context 'optional attributes' do
      it 'includes app_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('opt', required_attrs.merge(app_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'opt')
        expect(config).to have_key('app_id')
      end

      it 'omits app_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'minimal')
        expect(config).not_to have_key('app_id')
      end
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'minimal')
        expect(config).not_to have_key('name')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:secret]
        expect(sensitive_fields).to include(:secret)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_calls_sfu_app', 'typed')
        expect(config['account_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_calls_sfu_app('first', required_attrs)
        synth.cloudflare_calls_sfu_app('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_calls_sfu_app')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_calls_sfu_app,
    method: :cloudflare_calls_sfu_app,
    required_attrs: { account_id: 'test-value' },
    expected_outputs: [:id, :created, :modified, :name, :secret, :uid],
    sensitive_fields: [:secret],
    immutable_fields: [],
    boolean_fields: []
end
