# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_tunnel_cloudflared resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustTunnelCloudflared do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_tunnel_cloudflared' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'test')
        validate_required_attributes(config, [:account_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_tunnel_cloudflared('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_tunnel_cloudflared)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_tunnel_cloudflared('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.id}")
        expect(ref.account_tag).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.account_tag}")
        expect(ref.config_src).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.config_src}")
        expect(ref.connections).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.connections}")
        expect(ref.conns_active_at).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.conns_active_at}")
        expect(ref.conns_inactive_at).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.conns_inactive_at}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.created_at}")
        expect(ref.deleted_at).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.deleted_at}")
        expect(ref.metadata).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.metadata}")
        expect(ref.remote_config).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.remote_config}")
        expect(ref.status).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.status}")
        expect(ref.tun_type).to eq("${cloudflare_zero_trust_tunnel_cloudflared.test.tun_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'test')
        expect(config).not_to have_key('account_tag')
        expect(config).not_to have_key('config_src')
        expect(config).not_to have_key('connections')
        expect(config).not_to have_key('conns_active_at')
        expect(config).not_to have_key('conns_inactive_at')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('deleted_at')
        expect(config).not_to have_key('metadata')
        expect(config).not_to have_key('remote_config')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('tun_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ config_src: 'test-value', tunnel_secret: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'full')
        expect(config).to have_key('config_src')
        expect(config).to have_key('tunnel_secret')
      end
    end

    context 'optional attributes' do
      it 'includes config_src when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('opt', required_attrs.merge(config_src: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'opt')
        expect(config).to have_key('config_src')
      end

      it 'omits config_src when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'minimal')
        expect(config).not_to have_key('config_src')
      end
      it 'includes tunnel_secret when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('opt', required_attrs.merge(tunnel_secret: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'opt')
        expect(config).to have_key('tunnel_secret')
      end

      it 'omits tunnel_secret when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'minimal')
        expect(config).not_to have_key('tunnel_secret')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:tunnel_secret]
        expect(sensitive_fields).to include(:tunnel_secret)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_tunnel_cloudflared', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_tunnel_cloudflared('first', required_attrs)
        synth.cloudflare_zero_trust_tunnel_cloudflared('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_tunnel_cloudflared')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_tunnel_cloudflared,
    method: :cloudflare_zero_trust_tunnel_cloudflared,
    required_attrs: { account_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :account_tag, :config_src, :connections, :conns_active_at, :conns_inactive_at, :created_at, :deleted_at, :metadata, :remote_config, :status, :tun_type],
    sensitive_fields: [:tunnel_secret],
    immutable_fields: [],
    boolean_fields: []
end
