# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_dlp_custom_profile resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustDlpCustomProfile do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_dlp_custom_profile' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'test')
        validate_required_attributes(config, [:account_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dlp_custom_profile('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_dlp_custom_profile)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dlp_custom_profile('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.id}")
        expect(ref.ai_context_enabled).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.ai_context_enabled}")
        expect(ref.allowed_match_count).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.allowed_match_count}")
        expect(ref.confidence_threshold).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.confidence_threshold}")
        expect(ref.context_awareness).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.context_awareness}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.created_at}")
        expect(ref.ocr_enabled).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.ocr_enabled}")
        expect(ref.open_access).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.open_access}")
        expect(ref.type).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.type}")
        expect(ref.updated_at).to eq("${cloudflare_zero_trust_dlp_custom_profile.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'test')
        expect(config).not_to have_key('ai_context_enabled')
        expect(config).not_to have_key('allowed_match_count')
        expect(config).not_to have_key('confidence_threshold')
        expect(config).not_to have_key('context_awareness')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('ocr_enabled')
        expect(config).not_to have_key('open_access')
        expect(config).not_to have_key('type')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ ai_context_enabled: true, allowed_match_count: 3.14, confidence_threshold: 'test-value', context_awareness: { 'key1' => 'val1' }, description: 'test-value', entries: [{ 'key1' => 'val1' }], ocr_enabled: true, shared_entries: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'full')
        expect(config).to have_key('ai_context_enabled')
        expect(config).to have_key('allowed_match_count')
        expect(config).to have_key('confidence_threshold')
        expect(config).to have_key('context_awareness')
        expect(config).to have_key('description')
        expect(config).to have_key('entries')
        expect(config).to have_key('ocr_enabled')
        expect(config).to have_key('shared_entries')
      end
    end

    context 'optional attributes' do
      it 'includes ai_context_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(ai_context_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('ai_context_enabled')
      end

      it 'omits ai_context_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('ai_context_enabled')
      end
      it 'includes allowed_match_count when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(allowed_match_count: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('allowed_match_count')
      end

      it 'omits allowed_match_count when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('allowed_match_count')
      end
      it 'includes confidence_threshold when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(confidence_threshold: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('confidence_threshold')
      end

      it 'omits confidence_threshold when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('confidence_threshold')
      end
      it 'includes context_awareness when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(context_awareness: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('context_awareness')
      end

      it 'omits context_awareness when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('context_awareness')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes entries when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(entries: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('entries')
      end

      it 'omits entries when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('entries')
      end
      it 'includes ocr_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(ocr_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('ocr_enabled')
      end

      it 'omits ocr_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('ocr_enabled')
      end
      it 'includes shared_entries when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('opt', required_attrs.merge(shared_entries: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'opt')
        expect(config).to have_key('shared_entries')
      end

      it 'omits shared_entries when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'minimal')
        expect(config).not_to have_key('shared_entries')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts ai_context_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ai_context_enabled: val)
          synth.cloudflare_zero_trust_dlp_custom_profile("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', "bool_#{val}")
          expect(config['ai_context_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ocr_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ocr_enabled: val)
          synth.cloudflare_zero_trust_dlp_custom_profile("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', "bool_#{val}")
          expect(config['ocr_enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dlp_custom_profile', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dlp_custom_profile('first', required_attrs)
        synth.cloudflare_zero_trust_dlp_custom_profile('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_dlp_custom_profile')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_dlp_custom_profile,
    method: :cloudflare_zero_trust_dlp_custom_profile,
    required_attrs: { account_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :ai_context_enabled, :allowed_match_count, :confidence_threshold, :context_awareness, :created_at, :ocr_enabled, :open_access, :type, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:ai_context_enabled, :ocr_enabled]
end
