# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_dex_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustDexRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', match: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_dex_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dex_rule', 'test')
        validate_required_attributes(config, [:account_id, :match, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dex_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_dex_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dex_rule('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_dex_rule.test.id}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_dex_rule.test.created_at}")
        expect(ref.targeted_tests).to eq("${cloudflare_zero_trust_dex_rule.test.targeted_tests}")
        expect(ref.updated_at).to eq("${cloudflare_zero_trust_dex_rule.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dex_rule', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('targeted_tests')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dex_rule', 'full')
        expect(config).to have_key('description')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dex_rule', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dex_rule', 'minimal')
        expect(config).not_to have_key('description')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dex_rule', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['match']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dex_rule('first', required_attrs)
        synth.cloudflare_zero_trust_dex_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_dex_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_dex_rule,
    method: :cloudflare_zero_trust_dex_rule,
    required_attrs: { account_id: 'test-value', match: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :created_at, :targeted_tests, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
