# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_byo_ip_prefix resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareByoIpPrefix do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', asn: 3.14, cidr: 'test-value' } }

  describe ':cloudflare_byo_ip_prefix' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'test')
        validate_required_attributes(config, [:account_id, :asn, :cidr])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_byo_ip_prefix('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_byo_ip_prefix)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_byo_ip_prefix('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_byo_ip_prefix.test.id}")
        expect(ref.advertised).to eq("${cloudflare_byo_ip_prefix.test.advertised}")
        expect(ref.advertised_modified_at).to eq("${cloudflare_byo_ip_prefix.test.advertised_modified_at}")
        expect(ref.approved).to eq("${cloudflare_byo_ip_prefix.test.approved}")
        expect(ref.created_at).to eq("${cloudflare_byo_ip_prefix.test.created_at}")
        expect(ref.delegate_loa_creation).to eq("${cloudflare_byo_ip_prefix.test.delegate_loa_creation}")
        expect(ref.irr_validation_state).to eq("${cloudflare_byo_ip_prefix.test.irr_validation_state}")
        expect(ref.modified_at).to eq("${cloudflare_byo_ip_prefix.test.modified_at}")
        expect(ref.on_demand_enabled).to eq("${cloudflare_byo_ip_prefix.test.on_demand_enabled}")
        expect(ref.on_demand_locked).to eq("${cloudflare_byo_ip_prefix.test.on_demand_locked}")
        expect(ref.ownership_validation_state).to eq("${cloudflare_byo_ip_prefix.test.ownership_validation_state}")
        expect(ref.ownership_validation_token).to eq("${cloudflare_byo_ip_prefix.test.ownership_validation_token}")
        expect(ref.rpki_validation_state).to eq("${cloudflare_byo_ip_prefix.test.rpki_validation_state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'test')
        expect(config).not_to have_key('advertised')
        expect(config).not_to have_key('advertised_modified_at')
        expect(config).not_to have_key('approved')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('delegate_loa_creation')
        expect(config).not_to have_key('irr_validation_state')
        expect(config).not_to have_key('modified_at')
        expect(config).not_to have_key('on_demand_enabled')
        expect(config).not_to have_key('on_demand_locked')
        expect(config).not_to have_key('ownership_validation_state')
        expect(config).not_to have_key('ownership_validation_token')
        expect(config).not_to have_key('rpki_validation_state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ delegate_loa_creation: true, description: 'test-value', loa_document_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'full')
        expect(config).to have_key('delegate_loa_creation')
        expect(config).to have_key('description')
        expect(config).to have_key('loa_document_id')
      end
    end

    context 'optional attributes' do
      it 'includes delegate_loa_creation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('opt', required_attrs.merge(delegate_loa_creation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'opt')
        expect(config).to have_key('delegate_loa_creation')
      end

      it 'omits delegate_loa_creation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'minimal')
        expect(config).not_to have_key('delegate_loa_creation')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes loa_document_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('opt', required_attrs.merge(loa_document_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'opt')
        expect(config).to have_key('loa_document_id')
      end

      it 'omits loa_document_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'minimal')
        expect(config).not_to have_key('loa_document_id')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts delegate_loa_creation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delegate_loa_creation: val)
          synth.cloudflare_byo_ip_prefix("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', "bool_#{val}")
          expect(config['delegate_loa_creation']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_byo_ip_prefix', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['asn']).to be_a(Float)
        expect(config['cidr']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_byo_ip_prefix('first', required_attrs)
        synth.cloudflare_byo_ip_prefix('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_byo_ip_prefix')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_byo_ip_prefix,
    method: :cloudflare_byo_ip_prefix,
    required_attrs: { account_id: 'test-value', asn: 3.14, cidr: 'test-value' },
    expected_outputs: [:id, :advertised, :advertised_modified_at, :approved, :created_at, :delegate_loa_creation, :irr_validation_state, :modified_at, :on_demand_enabled, :on_demand_locked, :ownership_validation_state, :ownership_validation_token, :rpki_validation_state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:delegate_loa_creation]
end
