# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_dns_firewall resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareDnsFirewall do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', name: 'test-value', upstream_ips: ['test-value'] } }

  describe ':cloudflare_dns_firewall' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'test')
        validate_required_attributes(config, [:account_id, :name, :upstream_ips])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_dns_firewall('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_dns_firewall)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_dns_firewall('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_dns_firewall.test.id}")
        expect(ref.attack_mitigation).to eq("${cloudflare_dns_firewall.test.attack_mitigation}")
        expect(ref.dns_firewall_ips).to eq("${cloudflare_dns_firewall.test.dns_firewall_ips}")
        expect(ref.maximum_cache_ttl).to eq("${cloudflare_dns_firewall.test.maximum_cache_ttl}")
        expect(ref.minimum_cache_ttl).to eq("${cloudflare_dns_firewall.test.minimum_cache_ttl}")
        expect(ref.modified_on).to eq("${cloudflare_dns_firewall.test.modified_on}")
        expect(ref.retries).to eq("${cloudflare_dns_firewall.test.retries}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'test')
        expect(config).not_to have_key('attack_mitigation')
        expect(config).not_to have_key('dns_firewall_ips')
        expect(config).not_to have_key('maximum_cache_ttl')
        expect(config).not_to have_key('minimum_cache_ttl')
        expect(config).not_to have_key('modified_on')
        expect(config).not_to have_key('retries')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ attack_mitigation: { 'key1' => 'val1' }, deprecate_any_requests: true, ecs_fallback: true, maximum_cache_ttl: 3.14, minimum_cache_ttl: 3.14, negative_cache_ttl: 3.14, ratelimit: 3.14, retries: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'full')
        expect(config).to have_key('attack_mitigation')
        expect(config).to have_key('deprecate_any_requests')
        expect(config).to have_key('ecs_fallback')
        expect(config).to have_key('maximum_cache_ttl')
        expect(config).to have_key('minimum_cache_ttl')
        expect(config).to have_key('negative_cache_ttl')
        expect(config).to have_key('ratelimit')
        expect(config).to have_key('retries')
      end
    end

    context 'optional attributes' do
      it 'includes attack_mitigation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(attack_mitigation: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('attack_mitigation')
      end

      it 'omits attack_mitigation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('attack_mitigation')
      end
      it 'includes deprecate_any_requests when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(deprecate_any_requests: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('deprecate_any_requests')
      end

      it 'omits deprecate_any_requests when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('deprecate_any_requests')
      end
      it 'includes ecs_fallback when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(ecs_fallback: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('ecs_fallback')
      end

      it 'omits ecs_fallback when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('ecs_fallback')
      end
      it 'includes maximum_cache_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(maximum_cache_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('maximum_cache_ttl')
      end

      it 'omits maximum_cache_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('maximum_cache_ttl')
      end
      it 'includes minimum_cache_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(minimum_cache_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('minimum_cache_ttl')
      end

      it 'omits minimum_cache_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('minimum_cache_ttl')
      end
      it 'includes negative_cache_ttl when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(negative_cache_ttl: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('negative_cache_ttl')
      end

      it 'omits negative_cache_ttl when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('negative_cache_ttl')
      end
      it 'includes ratelimit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(ratelimit: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('ratelimit')
      end

      it 'omits ratelimit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('ratelimit')
      end
      it 'includes retries when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('opt', required_attrs.merge(retries: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'opt')
        expect(config).to have_key('retries')
      end

      it 'omits retries when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'minimal')
        expect(config).not_to have_key('retries')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts deprecate_any_requests=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(deprecate_any_requests: val)
          synth.cloudflare_dns_firewall("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_dns_firewall', "bool_#{val}")
          expect(config['deprecate_any_requests']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ecs_fallback=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ecs_fallback: val)
          synth.cloudflare_dns_firewall("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_dns_firewall', "bool_#{val}")
          expect(config['ecs_fallback']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_dns_firewall', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['upstream_ips']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_dns_firewall('first', required_attrs)
        synth.cloudflare_dns_firewall('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_dns_firewall')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_dns_firewall,
    method: :cloudflare_dns_firewall,
    required_attrs: { account_id: 'test-value', name: 'test-value', upstream_ips: ['test-value'] },
    expected_outputs: [:id, :attack_mitigation, :dns_firewall_ips, :maximum_cache_ttl, :minimum_cache_ttl, :modified_on, :retries],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:deprecate_any_requests, :ecs_fallback]
end
