# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_custom_hostname resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareCustomHostname do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { hostname: 'test-value', ssl: { 'key1' => 'val1' }, zone_id: 'test-value' } }

  describe ':cloudflare_custom_hostname' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'test')
        validate_required_attributes(config, [:hostname, :ssl, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_custom_hostname('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_custom_hostname)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_custom_hostname('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_custom_hostname.test.id}")
        expect(ref.created_at).to eq("${cloudflare_custom_hostname.test.created_at}")
        expect(ref.ownership_verification).to eq("${cloudflare_custom_hostname.test.ownership_verification}")
        expect(ref.ownership_verification_http).to eq("${cloudflare_custom_hostname.test.ownership_verification_http}")
        expect(ref.status).to eq("${cloudflare_custom_hostname.test.status}")
        expect(ref.verification_errors).to eq("${cloudflare_custom_hostname.test.verification_errors}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('ownership_verification')
        expect(config).not_to have_key('ownership_verification_http')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('verification_errors')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_metadata: { 'key1' => 'val1' }, custom_origin_server: 'test-value', custom_origin_sni: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'full')
        expect(config).to have_key('custom_metadata')
        expect(config).to have_key('custom_origin_server')
        expect(config).to have_key('custom_origin_sni')
      end
    end

    context 'optional attributes' do
      it 'includes custom_metadata when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('opt', required_attrs.merge(custom_metadata: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'opt')
        expect(config).to have_key('custom_metadata')
      end

      it 'omits custom_metadata when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'minimal')
        expect(config).not_to have_key('custom_metadata')
      end
      it 'includes custom_origin_server when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('opt', required_attrs.merge(custom_origin_server: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'opt')
        expect(config).to have_key('custom_origin_server')
      end

      it 'omits custom_origin_server when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'minimal')
        expect(config).not_to have_key('custom_origin_server')
      end
      it 'includes custom_origin_sni when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('opt', required_attrs.merge(custom_origin_sni: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'opt')
        expect(config).to have_key('custom_origin_sni')
      end

      it 'omits custom_origin_sni when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'minimal')
        expect(config).not_to have_key('custom_origin_sni')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_hostname', 'typed')
        expect(config['hostname']).to be_a(String)
        expect(config['ssl']).to be_a(Hash)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_hostname('first', required_attrs)
        synth.cloudflare_custom_hostname('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_custom_hostname')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_custom_hostname,
    method: :cloudflare_custom_hostname,
    required_attrs: { hostname: 'test-value', ssl: { 'key1' => 'val1' }, zone_id: 'test-value' },
    expected_outputs: [:id, :created_at, :ownership_verification, :ownership_verification_http, :status, :verification_errors],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
