# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_dns_location resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustDnsLocation do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_dns_location' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'test')
        validate_required_attributes(config, [:account_id, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dns_location('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_dns_location)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_dns_location('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_dns_location.test.id}")
        expect(ref.client_default).to eq("${cloudflare_zero_trust_dns_location.test.client_default}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_dns_location.test.created_at}")
        expect(ref.dns_destination_ips_id).to eq("${cloudflare_zero_trust_dns_location.test.dns_destination_ips_id}")
        expect(ref.dns_destination_ipv6_block_id).to eq("${cloudflare_zero_trust_dns_location.test.dns_destination_ipv6_block_id}")
        expect(ref.doh_subdomain).to eq("${cloudflare_zero_trust_dns_location.test.doh_subdomain}")
        expect(ref.ecs_support).to eq("${cloudflare_zero_trust_dns_location.test.ecs_support}")
        expect(ref.ip).to eq("${cloudflare_zero_trust_dns_location.test.ip}")
        expect(ref.ipv4_destination).to eq("${cloudflare_zero_trust_dns_location.test.ipv4_destination}")
        expect(ref.ipv4_destination_backup).to eq("${cloudflare_zero_trust_dns_location.test.ipv4_destination_backup}")
        expect(ref.networks).to eq("${cloudflare_zero_trust_dns_location.test.networks}")
        expect(ref.updated_at).to eq("${cloudflare_zero_trust_dns_location.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'test')
        expect(config).not_to have_key('client_default')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('dns_destination_ips_id')
        expect(config).not_to have_key('dns_destination_ipv6_block_id')
        expect(config).not_to have_key('doh_subdomain')
        expect(config).not_to have_key('ecs_support')
        expect(config).not_to have_key('ip')
        expect(config).not_to have_key('ipv4_destination')
        expect(config).not_to have_key('ipv4_destination_backup')
        expect(config).not_to have_key('networks')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ client_default: true, dns_destination_ips_id: 'test-value', ecs_support: true, endpoints: { 'key1' => 'val1' }, networks: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'full')
        expect(config).to have_key('client_default')
        expect(config).to have_key('dns_destination_ips_id')
        expect(config).to have_key('ecs_support')
        expect(config).to have_key('endpoints')
        expect(config).to have_key('networks')
      end
    end

    context 'optional attributes' do
      it 'includes client_default when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('opt', required_attrs.merge(client_default: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'opt')
        expect(config).to have_key('client_default')
      end

      it 'omits client_default when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'minimal')
        expect(config).not_to have_key('client_default')
      end
      it 'includes dns_destination_ips_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('opt', required_attrs.merge(dns_destination_ips_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'opt')
        expect(config).to have_key('dns_destination_ips_id')
      end

      it 'omits dns_destination_ips_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'minimal')
        expect(config).not_to have_key('dns_destination_ips_id')
      end
      it 'includes ecs_support when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('opt', required_attrs.merge(ecs_support: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'opt')
        expect(config).to have_key('ecs_support')
      end

      it 'omits ecs_support when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'minimal')
        expect(config).not_to have_key('ecs_support')
      end
      it 'includes endpoints when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('opt', required_attrs.merge(endpoints: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'opt')
        expect(config).to have_key('endpoints')
      end

      it 'omits endpoints when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'minimal')
        expect(config).not_to have_key('endpoints')
      end
      it 'includes networks when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('opt', required_attrs.merge(networks: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'opt')
        expect(config).to have_key('networks')
      end

      it 'omits networks when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'minimal')
        expect(config).not_to have_key('networks')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts client_default=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(client_default: val)
          synth.cloudflare_zero_trust_dns_location("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', "bool_#{val}")
          expect(config['client_default']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts ecs_support=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(ecs_support: val)
          synth.cloudflare_zero_trust_dns_location("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', "bool_#{val}")
          expect(config['ecs_support']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_dns_location', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_dns_location('first', required_attrs)
        synth.cloudflare_zero_trust_dns_location('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_dns_location')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_dns_location,
    method: :cloudflare_zero_trust_dns_location,
    required_attrs: { account_id: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :client_default, :created_at, :dns_destination_ips_id, :dns_destination_ipv6_block_id, :doh_subdomain, :ecs_support, :ip, :ipv4_destination, :ipv4_destination_backup, :networks, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:client_default, :ecs_support]
end
