# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_healthcheck resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareHealthcheck do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { address: 'test-value', name: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_healthcheck' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'test')
        validate_required_attributes(config, [:address, :name, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_healthcheck('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_healthcheck)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_healthcheck('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_healthcheck.test.id}")
        expect(ref.consecutive_fails).to eq("${cloudflare_healthcheck.test.consecutive_fails}")
        expect(ref.consecutive_successes).to eq("${cloudflare_healthcheck.test.consecutive_successes}")
        expect(ref.created_on).to eq("${cloudflare_healthcheck.test.created_on}")
        expect(ref.failure_reason).to eq("${cloudflare_healthcheck.test.failure_reason}")
        expect(ref.http_config).to eq("${cloudflare_healthcheck.test.http_config}")
        expect(ref.interval).to eq("${cloudflare_healthcheck.test.interval}")
        expect(ref.modified_on).to eq("${cloudflare_healthcheck.test.modified_on}")
        expect(ref.retries).to eq("${cloudflare_healthcheck.test.retries}")
        expect(ref.status).to eq("${cloudflare_healthcheck.test.status}")
        expect(ref.suspended).to eq("${cloudflare_healthcheck.test.suspended}")
        expect(ref.tcp_config).to eq("${cloudflare_healthcheck.test.tcp_config}")
        expect(ref.timeout).to eq("${cloudflare_healthcheck.test.timeout}")
        expect(ref.type).to eq("${cloudflare_healthcheck.test.type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'test')
        expect(config).not_to have_key('consecutive_fails')
        expect(config).not_to have_key('consecutive_successes')
        expect(config).not_to have_key('created_on')
        expect(config).not_to have_key('failure_reason')
        expect(config).not_to have_key('http_config')
        expect(config).not_to have_key('interval')
        expect(config).not_to have_key('modified_on')
        expect(config).not_to have_key('retries')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('suspended')
        expect(config).not_to have_key('tcp_config')
        expect(config).not_to have_key('timeout')
        expect(config).not_to have_key('type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ check_regions: ['test-value'], consecutive_fails: 3.14, consecutive_successes: 3.14, description: 'test-value', http_config: { 'key1' => 'val1' }, interval: 3.14, retries: 3.14, suspended: true, tcp_config: { 'key1' => 'val1' }, timeout: 3.14, type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'full')
        expect(config).to have_key('check_regions')
        expect(config).to have_key('consecutive_fails')
        expect(config).to have_key('consecutive_successes')
        expect(config).to have_key('description')
        expect(config).to have_key('http_config')
        expect(config).to have_key('interval')
        expect(config).to have_key('retries')
        expect(config).to have_key('suspended')
        expect(config).to have_key('tcp_config')
        expect(config).to have_key('timeout')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes check_regions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(check_regions: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('check_regions')
      end

      it 'omits check_regions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('check_regions')
      end
      it 'includes consecutive_fails when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(consecutive_fails: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('consecutive_fails')
      end

      it 'omits consecutive_fails when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('consecutive_fails')
      end
      it 'includes consecutive_successes when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(consecutive_successes: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('consecutive_successes')
      end

      it 'omits consecutive_successes when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('consecutive_successes')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes http_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(http_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('http_config')
      end

      it 'omits http_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('http_config')
      end
      it 'includes interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(interval: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('interval')
      end

      it 'omits interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('interval')
      end
      it 'includes retries when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(retries: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('retries')
      end

      it 'omits retries when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('retries')
      end
      it 'includes suspended when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(suspended: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('suspended')
      end

      it 'omits suspended when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('suspended')
      end
      it 'includes tcp_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(tcp_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('tcp_config')
      end

      it 'omits tcp_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('tcp_config')
      end
      it 'includes timeout when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(timeout: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('timeout')
      end

      it 'omits timeout when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('timeout')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts suspended=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(suspended: val)
          synth.cloudflare_healthcheck("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_healthcheck', "bool_#{val}")
          expect(config['suspended']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_healthcheck', 'typed')
        expect(config['address']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_healthcheck('first', required_attrs)
        synth.cloudflare_healthcheck('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_healthcheck')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_healthcheck,
    method: :cloudflare_healthcheck,
    required_attrs: { address: 'test-value', name: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :consecutive_fails, :consecutive_successes, :created_on, :failure_reason, :http_config, :interval, :modified_on, :retries, :status, :suspended, :tcp_config, :timeout, :type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:suspended]
end
