# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_gateway_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustGatewayPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', action: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_gateway_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'test')
        validate_required_attributes(config, [:account_id, :action, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_gateway_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_gateway_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_gateway_policy('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_gateway_policy.test.id}")
        expect(ref.created_at).to eq("${cloudflare_zero_trust_gateway_policy.test.created_at}")
        expect(ref.deleted_at).to eq("${cloudflare_zero_trust_gateway_policy.test.deleted_at}")
        expect(ref.device_posture).to eq("${cloudflare_zero_trust_gateway_policy.test.device_posture}")
        expect(ref.enabled).to eq("${cloudflare_zero_trust_gateway_policy.test.enabled}")
        expect(ref.expiration).to eq("${cloudflare_zero_trust_gateway_policy.test.expiration}")
        expect(ref.identity).to eq("${cloudflare_zero_trust_gateway_policy.test.identity}")
        expect(ref.precedence).to eq("${cloudflare_zero_trust_gateway_policy.test.precedence}")
        expect(ref.read_only).to eq("${cloudflare_zero_trust_gateway_policy.test.read_only}")
        expect(ref.rule_settings).to eq("${cloudflare_zero_trust_gateway_policy.test.rule_settings}")
        expect(ref.schedule).to eq("${cloudflare_zero_trust_gateway_policy.test.schedule}")
        expect(ref.sharable).to eq("${cloudflare_zero_trust_gateway_policy.test.sharable}")
        expect(ref.source_account).to eq("${cloudflare_zero_trust_gateway_policy.test.source_account}")
        expect(ref.traffic).to eq("${cloudflare_zero_trust_gateway_policy.test.traffic}")
        expect(ref.updated_at).to eq("${cloudflare_zero_trust_gateway_policy.test.updated_at}")
        expect(ref.version).to eq("${cloudflare_zero_trust_gateway_policy.test.version}")
        expect(ref.warning_status).to eq("${cloudflare_zero_trust_gateway_policy.test.warning_status}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('deleted_at')
        expect(config).not_to have_key('device_posture')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('expiration')
        expect(config).not_to have_key('identity')
        expect(config).not_to have_key('precedence')
        expect(config).not_to have_key('read_only')
        expect(config).not_to have_key('rule_settings')
        expect(config).not_to have_key('schedule')
        expect(config).not_to have_key('sharable')
        expect(config).not_to have_key('source_account')
        expect(config).not_to have_key('traffic')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('version')
        expect(config).not_to have_key('warning_status')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', device_posture: 'test-value', enabled: true, expiration: { 'key1' => 'val1' }, filters: ['test-value'], identity: 'test-value', precedence: 3.14, rule_settings: { 'key1' => 'val1' }, schedule: { 'key1' => 'val1' }, traffic: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('device_posture')
        expect(config).to have_key('enabled')
        expect(config).to have_key('expiration')
        expect(config).to have_key('filters')
        expect(config).to have_key('identity')
        expect(config).to have_key('precedence')
        expect(config).to have_key('rule_settings')
        expect(config).to have_key('schedule')
        expect(config).to have_key('traffic')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes device_posture when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(device_posture: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('device_posture')
      end

      it 'omits device_posture when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('device_posture')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes expiration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(expiration: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('expiration')
      end

      it 'omits expiration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('expiration')
      end
      it 'includes filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(filters: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('filters')
      end

      it 'omits filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('filters')
      end
      it 'includes identity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(identity: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('identity')
      end

      it 'omits identity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('identity')
      end
      it 'includes precedence when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(precedence: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('precedence')
      end

      it 'omits precedence when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('precedence')
      end
      it 'includes rule_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(rule_settings: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('rule_settings')
      end

      it 'omits rule_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('rule_settings')
      end
      it 'includes schedule when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(schedule: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('schedule')
      end

      it 'omits schedule when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('schedule')
      end
      it 'includes traffic when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('opt', required_attrs.merge(traffic: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'opt')
        expect(config).to have_key('traffic')
      end

      it 'omits traffic when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'minimal')
        expect(config).not_to have_key('traffic')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.cloudflare_zero_trust_gateway_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_gateway_policy', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['action']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_gateway_policy('first', required_attrs)
        synth.cloudflare_zero_trust_gateway_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_gateway_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_gateway_policy,
    method: :cloudflare_zero_trust_gateway_policy,
    required_attrs: { account_id: 'test-value', action: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :created_at, :deleted_at, :device_posture, :enabled, :expiration, :identity, :precedence, :read_only, :rule_settings, :schedule, :sharable, :source_account, :traffic, :updated_at, :version, :warning_status],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
