# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_origin_ca_certificate resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareOriginCaCertificate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { csr: 'test-value', hostnames: ['test-value'], request_type: 'test-value' } }

  describe ':cloudflare_origin_ca_certificate' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_origin_ca_certificate', 'test')
        validate_required_attributes(config, [:csr, :hostnames, :request_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_origin_ca_certificate('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_origin_ca_certificate)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_origin_ca_certificate('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_origin_ca_certificate.test.id}")
        expect(ref.certificate).to eq("${cloudflare_origin_ca_certificate.test.certificate}")
        expect(ref.expires_on).to eq("${cloudflare_origin_ca_certificate.test.expires_on}")
        expect(ref.requested_validity).to eq("${cloudflare_origin_ca_certificate.test.requested_validity}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_origin_ca_certificate', 'test')
        expect(config).not_to have_key('certificate')
        expect(config).not_to have_key('expires_on')
        expect(config).not_to have_key('requested_validity')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ requested_validity: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_origin_ca_certificate', 'full')
        expect(config).to have_key('requested_validity')
      end
    end

    context 'optional attributes' do
      it 'includes requested_validity when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('opt', required_attrs.merge(requested_validity: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_origin_ca_certificate', 'opt')
        expect(config).to have_key('requested_validity')
      end

      it 'omits requested_validity when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_origin_ca_certificate', 'minimal')
        expect(config).not_to have_key('requested_validity')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_origin_ca_certificate', 'typed')
        expect(config['csr']).to be_a(String)
        expect(config['hostnames']).to be_a(Array)
        expect(config['request_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_origin_ca_certificate('first', required_attrs)
        synth.cloudflare_origin_ca_certificate('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_origin_ca_certificate')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_origin_ca_certificate,
    method: :cloudflare_origin_ca_certificate,
    required_attrs: { csr: 'test-value', hostnames: ['test-value'], request_type: 'test-value' },
    expected_outputs: [:id, :certificate, :expires_on, :requested_validity],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
