# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_account_subscription resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareAccountSubscription do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value' } }

  describe ':cloudflare_account_subscription' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'test')
        validate_required_attributes(config, [:account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_account_subscription('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_account_subscription)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_account_subscription('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_account_subscription.test.id}")
        expect(ref.currency).to eq("${cloudflare_account_subscription.test.currency}")
        expect(ref.current_period_end).to eq("${cloudflare_account_subscription.test.current_period_end}")
        expect(ref.current_period_start).to eq("${cloudflare_account_subscription.test.current_period_start}")
        expect(ref.frequency).to eq("${cloudflare_account_subscription.test.frequency}")
        expect(ref.price).to eq("${cloudflare_account_subscription.test.price}")
        expect(ref.rate_plan).to eq("${cloudflare_account_subscription.test.rate_plan}")
        expect(ref.state).to eq("${cloudflare_account_subscription.test.state}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'test')
        expect(config).not_to have_key('currency')
        expect(config).not_to have_key('current_period_end')
        expect(config).not_to have_key('current_period_start')
        expect(config).not_to have_key('frequency')
        expect(config).not_to have_key('price')
        expect(config).not_to have_key('rate_plan')
        expect(config).not_to have_key('state')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ frequency: 'test-value', rate_plan: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'full')
        expect(config).to have_key('frequency')
        expect(config).to have_key('rate_plan')
      end
    end

    context 'optional attributes' do
      it 'includes frequency when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('opt', required_attrs.merge(frequency: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'opt')
        expect(config).to have_key('frequency')
      end

      it 'omits frequency when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'minimal')
        expect(config).not_to have_key('frequency')
      end
      it 'includes rate_plan when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('opt', required_attrs.merge(rate_plan: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'opt')
        expect(config).to have_key('rate_plan')
      end

      it 'omits rate_plan when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'minimal')
        expect(config).not_to have_key('rate_plan')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_account_subscription', 'typed')
        expect(config['account_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_account_subscription('first', required_attrs)
        synth.cloudflare_account_subscription('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_account_subscription')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_account_subscription,
    method: :cloudflare_account_subscription,
    required_attrs: { account_id: 'test-value' },
    expected_outputs: [:id, :currency, :current_period_end, :current_period_start, :frequency, :price, :rate_plan, :state],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
