# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_access_mtls_certificate resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustAccessMtlsCertificate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { certificate: 'test-value', name: 'test-value' } }

  describe ':cloudflare_zero_trust_access_mtls_certificate' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'test')
        validate_required_attributes(config, [:certificate, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_access_mtls_certificate('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_access_mtls_certificate)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_access_mtls_certificate('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_access_mtls_certificate.test.id}")
        expect(ref.associated_hostnames).to eq("${cloudflare_zero_trust_access_mtls_certificate.test.associated_hostnames}")
        expect(ref.expires_on).to eq("${cloudflare_zero_trust_access_mtls_certificate.test.expires_on}")
        expect(ref.fingerprint).to eq("${cloudflare_zero_trust_access_mtls_certificate.test.fingerprint}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'test')
        expect(config).not_to have_key('associated_hostnames')
        expect(config).not_to have_key('expires_on')
        expect(config).not_to have_key('fingerprint')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_id: 'test-value', associated_hostnames: ['test-value'], zone_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'full')
        expect(config).to have_key('account_id')
        expect(config).to have_key('associated_hostnames')
        expect(config).to have_key('zone_id')
      end
    end

    context 'optional attributes' do
      it 'includes account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('opt', required_attrs.merge(account_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'opt')
        expect(config).to have_key('account_id')
      end

      it 'omits account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'minimal')
        expect(config).not_to have_key('account_id')
      end
      it 'includes associated_hostnames when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('opt', required_attrs.merge(associated_hostnames: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'opt')
        expect(config).to have_key('associated_hostnames')
      end

      it 'omits associated_hostnames when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'minimal')
        expect(config).not_to have_key('associated_hostnames')
      end
      it 'includes zone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('opt', required_attrs.merge(zone_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'opt')
        expect(config).to have_key('zone_id')
      end

      it 'omits zone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'minimal')
        expect(config).not_to have_key('zone_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_mtls_certificate', 'typed')
        expect(config['certificate']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_mtls_certificate('first', required_attrs)
        synth.cloudflare_zero_trust_access_mtls_certificate('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_access_mtls_certificate')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_access_mtls_certificate,
    method: :cloudflare_zero_trust_access_mtls_certificate,
    required_attrs: { certificate: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :associated_hostnames, :expires_on, :fingerprint],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
