# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_r2_bucket_cors resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareR2BucketCors do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', bucket_name: 'test-value' } }

  describe ':cloudflare_r2_bucket_cors' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'test')
        validate_required_attributes(config, [:account_id, :bucket_name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_r2_bucket_cors('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_r2_bucket_cors)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_r2_bucket_cors('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_r2_bucket_cors.test.id}")
        expect(ref.jurisdiction).to eq("${cloudflare_r2_bucket_cors.test.jurisdiction}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'test')
        expect(config).not_to have_key('jurisdiction')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ jurisdiction: 'test-value', rules: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'full')
        expect(config).to have_key('jurisdiction')
        expect(config).to have_key('rules')
      end
    end

    context 'optional attributes' do
      it 'includes jurisdiction when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('opt', required_attrs.merge(jurisdiction: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'opt')
        expect(config).to have_key('jurisdiction')
      end

      it 'omits jurisdiction when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'minimal')
        expect(config).not_to have_key('jurisdiction')
      end
      it 'includes rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('opt', required_attrs.merge(rules: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'opt')
        expect(config).to have_key('rules')
      end

      it 'omits rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'minimal')
        expect(config).not_to have_key('rules')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_r2_bucket_cors', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['bucket_name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_r2_bucket_cors('first', required_attrs)
        synth.cloudflare_r2_bucket_cors('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_r2_bucket_cors')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_r2_bucket_cors,
    method: :cloudflare_r2_bucket_cors,
    required_attrs: { account_id: 'test-value', bucket_name: 'test-value' },
    expected_outputs: [:id, :jurisdiction],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
