# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_managed_transforms resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareManagedTransforms do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { managed_request_headers: [{ 'key1' => 'val1' }], managed_response_headers: [{ 'key1' => 'val1' }], zone_id: 'test-value' } }

  describe ':cloudflare_managed_transforms' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_managed_transforms('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_managed_transforms', 'test')
        validate_required_attributes(config, [:managed_request_headers, :managed_response_headers, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_managed_transforms('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_managed_transforms)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_managed_transforms('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_managed_transforms.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_managed_transforms('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_managed_transforms', 'typed')
        expect(config['managed_request_headers']).to be_a(Array)
        expect(config['managed_response_headers']).to be_a(Array)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_managed_transforms('first', required_attrs)
        synth.cloudflare_managed_transforms('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_managed_transforms')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_managed_transforms,
    method: :cloudflare_managed_transforms,
    required_attrs: { managed_request_headers: [{ 'key1' => 'val1' }], managed_response_headers: [{ 'key1' => 'val1' }], zone_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
