# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_stream_live_input resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareStreamLiveInput do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value' } }

  describe ':cloudflare_stream_live_input' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'test')
        validate_required_attributes(config, [:account_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_stream_live_input('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_stream_live_input)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_stream_live_input('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_stream_live_input.test.id}")
        expect(ref.created).to eq("${cloudflare_stream_live_input.test.created}")
        expect(ref.enabled).to eq("${cloudflare_stream_live_input.test.enabled}")
        expect(ref.modified).to eq("${cloudflare_stream_live_input.test.modified}")
        expect(ref.recording).to eq("${cloudflare_stream_live_input.test.recording}")
        expect(ref.rtmps).to eq("${cloudflare_stream_live_input.test.rtmps}")
        expect(ref.rtmps_playback).to eq("${cloudflare_stream_live_input.test.rtmps_playback}")
        expect(ref.srt).to eq("${cloudflare_stream_live_input.test.srt}")
        expect(ref.srt_playback).to eq("${cloudflare_stream_live_input.test.srt_playback}")
        expect(ref.status).to eq("${cloudflare_stream_live_input.test.status}")
        expect(ref.uid).to eq("${cloudflare_stream_live_input.test.uid}")
        expect(ref.web_rtc).to eq("${cloudflare_stream_live_input.test.web_rtc}")
        expect(ref.web_rtc_playback).to eq("${cloudflare_stream_live_input.test.web_rtc_playback}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'test')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('modified')
        expect(config).not_to have_key('recording')
        expect(config).not_to have_key('rtmps')
        expect(config).not_to have_key('rtmps_playback')
        expect(config).not_to have_key('srt')
        expect(config).not_to have_key('srt_playback')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('uid')
        expect(config).not_to have_key('web_rtc')
        expect(config).not_to have_key('web_rtc_playback')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ default_creator: 'test-value', delete_recording_after_days: 3.14, enabled: true, live_input_identifier: 'test-value', meta: 'test-value', recording: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'full')
        expect(config).to have_key('default_creator')
        expect(config).to have_key('delete_recording_after_days')
        expect(config).to have_key('enabled')
        expect(config).to have_key('live_input_identifier')
        expect(config).to have_key('meta')
        expect(config).to have_key('recording')
      end
    end

    context 'optional attributes' do
      it 'includes default_creator when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('opt', required_attrs.merge(default_creator: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'opt')
        expect(config).to have_key('default_creator')
      end

      it 'omits default_creator when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'minimal')
        expect(config).not_to have_key('default_creator')
      end
      it 'includes delete_recording_after_days when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('opt', required_attrs.merge(delete_recording_after_days: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'opt')
        expect(config).to have_key('delete_recording_after_days')
      end

      it 'omits delete_recording_after_days when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'minimal')
        expect(config).not_to have_key('delete_recording_after_days')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes live_input_identifier when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('opt', required_attrs.merge(live_input_identifier: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'opt')
        expect(config).to have_key('live_input_identifier')
      end

      it 'omits live_input_identifier when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'minimal')
        expect(config).not_to have_key('live_input_identifier')
      end
      it 'includes meta when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('opt', required_attrs.merge(meta: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'opt')
        expect(config).to have_key('meta')
      end

      it 'omits meta when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'minimal')
        expect(config).not_to have_key('meta')
      end
      it 'includes recording when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('opt', required_attrs.merge(recording: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'opt')
        expect(config).to have_key('recording')
      end

      it 'omits recording when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'minimal')
        expect(config).not_to have_key('recording')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.cloudflare_stream_live_input("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_stream_live_input', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_stream_live_input', 'typed')
        expect(config['account_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_stream_live_input('first', required_attrs)
        synth.cloudflare_stream_live_input('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_stream_live_input')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_stream_live_input,
    method: :cloudflare_stream_live_input,
    required_attrs: { account_id: 'test-value' },
    expected_outputs: [:id, :created, :enabled, :modified, :recording, :rtmps, :rtmps_playback, :srt, :srt_playback, :status, :uid, :web_rtc, :web_rtc_playback],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
