# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_image_variant resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareImageVariant do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', id: 'test-value', options: { 'key1' => 'val1' } } }

  describe ':cloudflare_image_variant' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_image_variant', 'test')
        validate_required_attributes(config, [:account_id, :id, :options])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_image_variant('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_image_variant)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_image_variant('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_image_variant.test.id}")
        expect(ref.never_require_signed_urls).to eq("${cloudflare_image_variant.test.never_require_signed_urls}")
        expect(ref.variant).to eq("${cloudflare_image_variant.test.variant}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_image_variant', 'test')
        expect(config).not_to have_key('never_require_signed_urls')
        expect(config).not_to have_key('variant')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ never_require_signed_urls: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_image_variant', 'full')
        expect(config).to have_key('never_require_signed_urls')
      end
    end

    context 'optional attributes' do
      it 'includes never_require_signed_urls when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('opt', required_attrs.merge(never_require_signed_urls: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_image_variant', 'opt')
        expect(config).to have_key('never_require_signed_urls')
      end

      it 'omits never_require_signed_urls when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_image_variant', 'minimal')
        expect(config).not_to have_key('never_require_signed_urls')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts never_require_signed_urls=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(never_require_signed_urls: val)
          synth.cloudflare_image_variant("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_image_variant', "bool_#{val}")
          expect(config['never_require_signed_urls']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_image_variant', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['id']).to be_a(String)
        expect(config['options']).to be_a(Hash)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_image_variant('first', required_attrs)
        synth.cloudflare_image_variant('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_image_variant')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_image_variant,
    method: :cloudflare_image_variant,
    required_attrs: { account_id: 'test-value', id: 'test-value', options: { 'key1' => 'val1' } },
    expected_outputs: [:id, :never_require_signed_urls, :variant],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:never_require_signed_urls]
end
