# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_notification_policy resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareNotificationPolicy do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { account_id: 'test-value', alert_type: 'test-value', mechanisms: { 'key1' => 'val1' }, name: 'test-value' } }

  describe ':cloudflare_notification_policy' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'test')
        validate_required_attributes(config, [:account_id, :alert_type, :mechanisms, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_notification_policy('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_notification_policy)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_notification_policy('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_notification_policy.test.id}")
        expect(ref.created).to eq("${cloudflare_notification_policy.test.created}")
        expect(ref.enabled).to eq("${cloudflare_notification_policy.test.enabled}")
        expect(ref.modified).to eq("${cloudflare_notification_policy.test.modified}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'test')
        expect(config).not_to have_key('created')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('modified')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ alert_interval: 'test-value', description: 'test-value', enabled: true, filters: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'full')
        expect(config).to have_key('alert_interval')
        expect(config).to have_key('description')
        expect(config).to have_key('enabled')
        expect(config).to have_key('filters')
      end
    end

    context 'optional attributes' do
      it 'includes alert_interval when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('opt', required_attrs.merge(alert_interval: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'opt')
        expect(config).to have_key('alert_interval')
      end

      it 'omits alert_interval when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'minimal')
        expect(config).not_to have_key('alert_interval')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes filters when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('opt', required_attrs.merge(filters: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'opt')
        expect(config).to have_key('filters')
      end

      it 'omits filters when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'minimal')
        expect(config).not_to have_key('filters')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.cloudflare_notification_policy("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'cloudflare_notification_policy', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_notification_policy', 'typed')
        expect(config['account_id']).to be_a(String)
        expect(config['alert_type']).to be_a(String)
        expect(config['mechanisms']).to be_a(Hash)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_notification_policy('first', required_attrs)
        synth.cloudflare_notification_policy('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_notification_policy')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_notification_policy,
    method: :cloudflare_notification_policy,
    required_attrs: { account_id: 'test-value', alert_type: 'test-value', mechanisms: { 'key1' => 'val1' }, name: 'test-value' },
    expected_outputs: [:id, :created, :enabled, :modified],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:enabled]
end
