# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_zero_trust_access_identity_provider resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareZeroTrustAccessIdentityProvider do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { config: { 'key1' => 'val1' }, name: 'test-value', type: 'test-value' } }

  describe ':cloudflare_zero_trust_access_identity_provider' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'test')
        validate_required_attributes(config, [:config, :name, :type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_access_identity_provider('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_zero_trust_access_identity_provider)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_zero_trust_access_identity_provider('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_zero_trust_access_identity_provider.test.id}")
        expect(ref.scim_config).to eq("${cloudflare_zero_trust_access_identity_provider.test.scim_config}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'test')
        expect(config).not_to have_key('scim_config')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ account_id: 'test-value', scim_config: { 'key1' => 'val1' }, zone_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'full')
        expect(config).to have_key('account_id')
        expect(config).to have_key('scim_config')
        expect(config).to have_key('zone_id')
      end
    end

    context 'optional attributes' do
      it 'includes account_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('opt', required_attrs.merge(account_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'opt')
        expect(config).to have_key('account_id')
      end

      it 'omits account_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'minimal')
        expect(config).not_to have_key('account_id')
      end
      it 'includes scim_config when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('opt', required_attrs.merge(scim_config: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'opt')
        expect(config).to have_key('scim_config')
      end

      it 'omits scim_config when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'minimal')
        expect(config).not_to have_key('scim_config')
      end
      it 'includes zone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('opt', required_attrs.merge(zone_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'opt')
        expect(config).to have_key('zone_id')
      end

      it 'omits zone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'minimal')
        expect(config).not_to have_key('zone_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_zero_trust_access_identity_provider', 'typed')
        expect(config['config']).to be_a(Hash)
        expect(config['name']).to be_a(String)
        expect(config['type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_zero_trust_access_identity_provider('first', required_attrs)
        synth.cloudflare_zero_trust_access_identity_provider('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_zero_trust_access_identity_provider')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_zero_trust_access_identity_provider,
    method: :cloudflare_zero_trust_access_identity_provider,
    required_attrs: { config: { 'key1' => 'val1' }, name: 'test-value', type: 'test-value' },
    expected_outputs: [:id, :scim_config],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
