# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_schema_validation_settings resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareSchemaValidationSettings do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { validation_default_mitigation_action: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_schema_validation_settings' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_schema_validation_settings('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_schema_validation_settings', 'test')
        validate_required_attributes(config, [:validation_default_mitigation_action, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_schema_validation_settings('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_schema_validation_settings)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_schema_validation_settings('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_schema_validation_settings.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ validation_override_mitigation_action: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_schema_validation_settings('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_schema_validation_settings', 'full')
        expect(config).to have_key('validation_override_mitigation_action')
      end
    end

    context 'optional attributes' do
      it 'includes validation_override_mitigation_action when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_schema_validation_settings('opt', required_attrs.merge(validation_override_mitigation_action: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_schema_validation_settings', 'opt')
        expect(config).to have_key('validation_override_mitigation_action')
      end

      it 'omits validation_override_mitigation_action when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_schema_validation_settings('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_schema_validation_settings', 'minimal')
        expect(config).not_to have_key('validation_override_mitigation_action')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_schema_validation_settings('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_schema_validation_settings', 'typed')
        expect(config['validation_default_mitigation_action']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_schema_validation_settings('first', required_attrs)
        synth.cloudflare_schema_validation_settings('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_schema_validation_settings')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_schema_validation_settings,
    method: :cloudflare_schema_validation_settings,
    required_attrs: { validation_default_mitigation_action: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
