# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_api_shield_schema resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareApiShieldSchema do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { file: 'test-value', kind: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_api_shield_schema' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'test')
        validate_required_attributes(config, [:file, :kind, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_api_shield_schema('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_api_shield_schema)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_api_shield_schema('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_api_shield_schema.test.id}")
        expect(ref.created_at).to eq("${cloudflare_api_shield_schema.test.created_at}")
        expect(ref.schema).to eq("${cloudflare_api_shield_schema.test.schema}")
        expect(ref.source).to eq("${cloudflare_api_shield_schema.test.source}")
        expect(ref.upload_details).to eq("${cloudflare_api_shield_schema.test.upload_details}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('schema')
        expect(config).not_to have_key('source')
        expect(config).not_to have_key('upload_details')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ name: 'test-value', schema_id: 'test-value', validation_enabled: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'full')
        expect(config).to have_key('name')
        expect(config).to have_key('schema_id')
        expect(config).to have_key('validation_enabled')
      end
    end

    context 'optional attributes' do
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'minimal')
        expect(config).not_to have_key('name')
      end
      it 'includes schema_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('opt', required_attrs.merge(schema_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'opt')
        expect(config).to have_key('schema_id')
      end

      it 'omits schema_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'minimal')
        expect(config).not_to have_key('schema_id')
      end
      it 'includes validation_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('opt', required_attrs.merge(validation_enabled: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'opt')
        expect(config).to have_key('validation_enabled')
      end

      it 'omits validation_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'minimal')
        expect(config).not_to have_key('validation_enabled')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_api_shield_schema', 'typed')
        expect(config['file']).to be_a(String)
        expect(config['kind']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_api_shield_schema('first', required_attrs)
        synth.cloudflare_api_shield_schema('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_api_shield_schema')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_api_shield_schema,
    method: :cloudflare_api_shield_schema,
    required_attrs: { file: 'test-value', kind: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :created_at, :schema, :source, :upload_details],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
