# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a cloudflare_custom_ssl resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::CloudflareCustomSsl do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { certificate: 'test-value', private_key: 'test-value', zone_id: 'test-value' } }

  describe ':cloudflare_custom_ssl' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'test')
        validate_required_attributes(config, [:certificate, :private_key, :zone_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_custom_ssl('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:cloudflare_custom_ssl)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.cloudflare_custom_ssl('test', required_attrs)

        expect(ref.id).to eq("${cloudflare_custom_ssl.test.id}")
        expect(ref.bundle_method).to eq("${cloudflare_custom_ssl.test.bundle_method}")
        expect(ref.expires_on).to eq("${cloudflare_custom_ssl.test.expires_on}")
        expect(ref.hosts).to eq("${cloudflare_custom_ssl.test.hosts}")
        expect(ref.issuer).to eq("${cloudflare_custom_ssl.test.issuer}")
        expect(ref.keyless_server).to eq("${cloudflare_custom_ssl.test.keyless_server}")
        expect(ref.modified_on).to eq("${cloudflare_custom_ssl.test.modified_on}")
        expect(ref.policy_restrictions).to eq("${cloudflare_custom_ssl.test.policy_restrictions}")
        expect(ref.priority).to eq("${cloudflare_custom_ssl.test.priority}")
        expect(ref.signature).to eq("${cloudflare_custom_ssl.test.signature}")
        expect(ref.status).to eq("${cloudflare_custom_ssl.test.status}")
        expect(ref.type).to eq("${cloudflare_custom_ssl.test.type}")
        expect(ref.uploaded_on).to eq("${cloudflare_custom_ssl.test.uploaded_on}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'test')
        expect(config).not_to have_key('bundle_method')
        expect(config).not_to have_key('expires_on')
        expect(config).not_to have_key('hosts')
        expect(config).not_to have_key('issuer')
        expect(config).not_to have_key('keyless_server')
        expect(config).not_to have_key('modified_on')
        expect(config).not_to have_key('policy_restrictions')
        expect(config).not_to have_key('priority')
        expect(config).not_to have_key('signature')
        expect(config).not_to have_key('status')
        expect(config).not_to have_key('type')
        expect(config).not_to have_key('uploaded_on')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ bundle_method: 'test-value', deploy: 'test-value', geo_restrictions: { 'key1' => 'val1' }, policy: 'test-value', type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'full')
        expect(config).to have_key('bundle_method')
        expect(config).to have_key('deploy')
        expect(config).to have_key('geo_restrictions')
        expect(config).to have_key('policy')
        expect(config).to have_key('type')
      end
    end

    context 'optional attributes' do
      it 'includes bundle_method when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('opt', required_attrs.merge(bundle_method: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'opt')
        expect(config).to have_key('bundle_method')
      end

      it 'omits bundle_method when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'minimal')
        expect(config).not_to have_key('bundle_method')
      end
      it 'includes deploy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('opt', required_attrs.merge(deploy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'opt')
        expect(config).to have_key('deploy')
      end

      it 'omits deploy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'minimal')
        expect(config).not_to have_key('deploy')
      end
      it 'includes geo_restrictions when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('opt', required_attrs.merge(geo_restrictions: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'opt')
        expect(config).to have_key('geo_restrictions')
      end

      it 'omits geo_restrictions when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'minimal')
        expect(config).not_to have_key('geo_restrictions')
      end
      it 'includes policy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('opt', required_attrs.merge(policy: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'opt')
        expect(config).to have_key('policy')
      end

      it 'omits policy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'minimal')
        expect(config).not_to have_key('policy')
      end
      it 'includes type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('opt', required_attrs.merge(type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'opt')
        expect(config).to have_key('type')
      end

      it 'omits type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'minimal')
        expect(config).not_to have_key('type')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:private_key]
        expect(sensitive_fields).to include(:private_key)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'cloudflare_custom_ssl', 'typed')
        expect(config['certificate']).to be_a(String)
        expect(config['private_key']).to be_a(String)
        expect(config['zone_id']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.cloudflare_custom_ssl('first', required_attrs)
        synth.cloudflare_custom_ssl('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'cloudflare_custom_ssl')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :cloudflare_custom_ssl,
    method: :cloudflare_custom_ssl,
    required_attrs: { certificate: 'test-value', private_key: 'test-value', zone_id: 'test-value' },
    expected_outputs: [:id, :bundle_method, :expires_on, :hosts, :issuer, :keyless_server, :modified_on, :policy_restrictions, :priority, :signature, :status, :type, :uploaded_on],
    sensitive_fields: [:private_key],
    immutable_fields: [],
    boolean_fields: []
end
