# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class RegionalHostnameAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :hostname, T::String
    attribute :region_key, T::String
    attribute :zone_id, T::String
    attribute? :routing, T::String.optional
  end
end
