# Code generated by pangea-forge.
# InSpec profile for verifying cloudflare_api_shield infrastructure state.
#
# Usage:
#   1. Create the resource using Pangea or Terraform
#   2. Set CLOUDFLARE_TOKEN and CLOUDFLARE_GATEWAY_URL environment variables
#   3. Run: inspec exec profiles/cloudflare_api_shield/ -t cloudflare://

control 'cloudflare_api_shield-exists' do
  impact 1.0
  title 'Manages a cloudflare_api_shield resource'
  desc 'Verify that the cloudflare_api_shield resource exists and has expected properties'

  describe cloudflare_api_shield(name: attribute('id')) do
    it { should exist }
    its('auth_id_characteristics') { should_not be_nil }
    its('zone_id') { should_not be_nil }
  end
end
