# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base_attributes'

module Pangea::Resources::Cloudflare::Types
  include Dry.Types()

  class ZeroTrustDlpEntryAttributes < Pangea::Resources::BaseAttributes
    T = Pangea::Resources::Cloudflare::Types

    attribute :account_id, T::String
    attribute :enabled, T::Bool
    attribute :name, T::String
    attribute :pattern, T::Hash
    attribute? :description, T::String.optional
    attribute? :profile_id, T::String.optional
    attribute? :type, T::String.optional
  end
end
